// const pois = [
  //   {
  //     id: 1,
  //     name: "Τα Ταμπακαριά της Χαλέπας",
  //     description: "Τα Ταμπακαριά της Χαλέπας μαζί με αυτά της Αγίας Κυριακής συναποτελούσαν τη σημαντικότερη βιομηχανική(για τα δεδομένα της Κρήτης) περιοχή των Χανίων και ίσως της Κρήτης, από τα μέσα του 19ου αιώνα έως και τη δεκαετία του 1970. Σήμερα, το τελευταίο εν λειτουργία βυρσοδεψείο του Χρήστου Φιλοΐτη στέκεται ακόμα σε πείσμα της των καιρών του αστικού εξευγενισμού και της παγκοσμιοποιημένης οικονομίας.  ",
  //     position: [35.51982, 24.03845],
  //     icon: "location_icon",
  //     image_source: "image source: https://www.chania-heritage.gr/"
  //   },
  //   {
  //     id: 2,
  //     name: "Ελληνικό Προξενείο",
  //     description: "Στο σημείο αυτό, εκτός από την υπέροχη θέα προς το κέντρο της πόλης, μπορούμε να παρατηρήσουμε το Ελληνικό, το Βρετανικό και το Γερμανικό Προξενείο και η αφήγηση μας πυκνώνει για την ιστορία της Χαλέπας,  ως τόπος φιλοξενίας της διπλωματίας του ύστερου 19ου αιώνα. Ένα από τα πιο ιστορικά κτήρια της Χαλέπας, κτίσθηκε από τον βαμβακέμπορο Χορτάτζη τον 19ο αιώνα. ",
  //     position: [35.51823571635969, 24.03572036417894],
  //     icon: "location_icon",
  //     image_source: "image source: ΚΛΑΔΟΥ-ΜΠΛΕΤΣΑ ΑΙΜΙΛΙΑ",
  //   },
  //   {
  //     id: 3,
  //     name: "Πρώην Γαλλική Σχολή",
  //     description: "Το υπέροχο και εκτεταμένο κτίριο της Γαλλικής σχολής, το οποίο έχει βιώσει αλλεπάλληλες αλλαγές χρήσεις, από ιδιωτική κατοικία Αιγύπτιου εμπόρου μέχρι την στέγαση  τη γαλλικής σχολής και της αρχιτεκτονικής σχολής του Πολυτεχνείου Κρήτης. ",
  //     position: [35.51860, 24.03783],
  //     icon: "location_icon",
  //     image_source: "image source: ",
  //   },
  //   {
  //     id: 4,
  //     name: "Σπίτι Ελευθερίου Βενιζέλου",
  //     description: "Το σπίτι του Ελευθερίου Βενιζέλου, το οποίο σήμερα στεγάζει το Μουσείο Ελευθερίου Βενιζέλου, αποτελεί ένα από τα σημαντικότερα κτίρια της Χαλέπας και ένα από τα πιο σημαντικά ιστορικά κτίρια των Χανίων. Το σπίτι αυτό, το οποίο χτίστηκε στα τέλη του 19ου αιώνα, ήταν η κατοικία του Ελευθερίου Βενιζέλου, ενός από τους πιο σημαντικούς πολιτικούς της Ελλάδας και πρωθυπουργού της χώρας σε διάφορες περιόδους. Το σπίτι αυτό αποτελεί ένα σημαντικό μνημείο της ιστορίας της Ελλάδας και της Χαλέπας και είναι ένας δημοφιλής προορισμός για τους επισκέπτες που ενδιαφέρονται για την ιστορία και την πολιτική της χώρας.",
  //     position: [35.51835, 24.03869],
  //     icon: "location_icon",
  //     image_source: " ",
  //   },
  //   {
  //     id: 5,
  //     name: "Γαλλικό Προξενείο",
  //     description: "Το πρόσφατα ανακαινισμένο κτίριο του γάλλου προξένου Blanc μας προσφέρει τη δυνατότητα να αναλογιστούμε και να φανταστούμε τη μεγαλοπρεπή διάσταση του ανατολικού προαστείου των Χανίων, όπως αυτή είχε διαμορφωθεί προς τις τελευταίες δεκαετίες του 19ου αιώνα.",
  //     position: [35.51763, 24.03995],
  //     icon: "location_icon",
  //     image_source: " ",
  //   },
  //   {
  //     id: 6,
  //     name: "Παλάτι Πρίγκιπα Γεωργίου",
  //     description: "Το Παλάτι του Πρίγκιπα Γεωργίου, το οποίο βρίσκεται στην περιοχή της Χαλέπας, αποτελεί ένα από τα σημαντικότερα ιστορικά κτίρια των Χανίων και ένα από τα πιο σημαντικά μνημεία της νεότερης ιστορίας της Ελλάδας. Το παλάτι αυτό χτίστηκε στα τέλη του 19ου αιώνα για τον Πρίγκιπα Γεώργιο, τον δεύτερο γιο του βασιλιά Γεωργίου Α' της Ελλάδας. Το παλάτι αυτό αποτελεί ένα σημαντικό μνημείο της ιστορίας της Ελλάδας και της Χαλέπας και είναι ένας δημοφιλής προορισμός για τους επισκέπτες που ενδιαφέρονται για την ιστορία και την αρχιτεκτονική της χώρας.",
  //     position: [35.51865, 24.03831],
  //     icon: "location_icon",
  //     image_source: " ",
  //   },
  //   {
  //     id: 7,
  //     name: "Γερμανικό Προξενείο",
  //     description: "Το κτίριο που στέγαζε το γερμανικό προξενείο μέχρι και την περίοδο της Κρητικής Πολιτείας κατασκευάστηκε το 1870 από οθωμανό ανώτατο αξιωματούχο. Διέμενε στο κτίριο αυτό και ο Ρεούφ Πασάς των Χανίων, ο δημιουργός του Δημοτικού Κήπου.  Αποτέλεσε τη διπλωματική βάση όλων των μετεξελίξεων του γερμανικού κράτους, ακόμα και την περίοδο της ναζισμού. Κατά τη γερμανική κατοχή της Κρήτης στέγασε την γενική διοίκηση των κατοχών αρχών και φημολογείται ότι φιλοξένησε τον Έρβιν Ρόμμελ κατά την επιστροφή του από το βορειοαφρικανικό μέτωπο. ",
  //     position: [35.51775, 24.0355],
  //     icon: "location_icon",
  //     image_source: " ",
  //   },
  //   {
  //     id: 8,
  //     name: "Βρετανικό Προξενείο",
  //     description: "",
  //     position: [35.51789, 24.03618],
  //     icon: "location_icon",
  //     image_source: " ",
  //   },
  //   {
  //     id: 9,
  //     name: "Γερμανόφωνη καθολική εκκλησία",
  //     description: "",
  //     position: [35.51786, 24.03915],
  //     icon: "location_icon",
  //     image_source: " ",
  //   },
  //   {
  //     id: 10,
  //     name: "Πλατεία Έλενα Βενιζέλου",
  //     description: "",
  //     position: [35.51786, 24.03886],
  //     icon: "location_icon",
  //     image_source: " ",
  //   },
  //   {
  //     id: 11,
  //     name: "Εθνικό Ιδρυμα Ερευνών & Μελετών Ελευθέριος Βενιζέλος ",
  //     description: "Η πρώην οικία Μπλούμ κατασκευάστηκε στα μέσα του 19ου αιώνα από τον ομογενή έμπορο της Βεγγάζης, Εμμανουήλ Μπλούμ. Κατά την περίοδο της Κρητικής Πολιτείας στέγασε για λίγο το ιταλικό προξενείο, ενώ μετά τον θάνατο του Μπλούμ το 1911, μέρος της ιδιοκτησίας πέρασε στην ελληνική κοινότητα της Βεγγάζης, ώσπου το όλο συγκρότημα αγοράστηκε από το Ίδρυμα Βενιζέλος και το 2005 μετά από ανακαίνιση του κτιρίου στέγασε όλες τις λειτουργίες του ιδρύματος. ",
  //     position: [35.51796, 24.03888],
  //     icon: "location_icon",
  //     image_source: " ",
  //   },
  //   {
  //     id: 12,
  //     name: "Οικία Μαρκαντωνάκη",
  //     description: "Η Οικία της οικογένειας Μαρκαντωνάκη στη Χαλέπα Χανίων,κατασκευάστηκε αρχικά από τον αιγυπτιώτη Χορτάτζη το 1883. Ο Γεώργιος Χορτάτζης το κληροδότησε στην κόρη του Ερριέτα, η οποία παντρεύτηκε τον Πέτρο Μαρκαντωνάκη. Αποτελεί ιστορική βίλα της περιοχής, με ιδιαίτερη αρχιτεκτονική και με έναν υπέροχο κήπο. Το 1901, στο σπίτι αυτό κατοικούσε ο Γάλλος Συνταγματάρχης Émile Honoré Destelle.",
  //     position: [35.51691, 24.03946],
  //     icon: "location_icon",
  //     image_source: " ",
  //   },
  //   {
  //     id: 13,
  //     name: "Βίλλα Σβαρτς",
  //     description: "Η μεγαλόπρεπη αυτή βίλα με τους ιωνικούς κίονες ταυτίστηκε με την Ελπίδα Μέλαινα, η οποία την αγόρασε το 1875 και διέμεινε σε αυτήν εκεί μέχρι τα τέλη του 1880, όταν άφησε για πάντα την αγαπημένη της Χαλέπα, μετά από 20 χρόνια.  Μετέπειτα πέρασε στην ιδιοκτησία του γερμανού προξένου Ριχάρδου  Κρούγκερ, όπου και έμενε ο αδερφός του Μαξ. Τις τελευταίες δεκαετίες καταρρέει και οι ελπίδες να αναστηλωθεί ολοένα και λιγοστεύουν.  ",
  //     position: [35.51557, 24.03926],
  //     icon: "location_icon",
  //     image_source: " ",
  //   },
  //   {
  //     id: 14,
  //     name: "Οικία Βαλερίου Καλούτση",
  //     description: "Το νεοκλασικό αυτό διώροφο κτίριο κατασκευάστηκε  στις αρχές του 20ου αιώνα από τον Βαλέριο Καλούτση, τον μετέπειτα σύζυγο της Φλωρεντίνης Σκουλούδη- Καλούτση. Το πλούσιο σε διάκοσμο αυτό κτίριο φιλοξένησε μεγάλες προσωπικότητες της κρητικής κοινωνίας μέχρι να αποτελέσει από τα μέσα του 20ου αιώνα την κύρια κατοικία και εργαστήριο της Φλωρεντίνης. Γιος της Φλωρεντίνης ήταν ο σπουδαίος εικαστικός και ζωγράφος Βαλέριος Καλούτσης.",
  //     position: [35.51606, 24.03855],
  //     icon: "location_icon",
  //     image_source: " ",
  //   },
  //   {
  //     id: 15,
  //     name: "Κατσαμπάς",
  //     description: "Μια ιστορική γωνιά της Χαλέπας, σταυροδρόμι συνοικιών και σημείο συνάντησης των Χανιωτών, όπου έζησαν σπουδαίες προσωπικότητες της πόλης μας, αλλά και συνδέθηκε με ένα ιδιαίτερο και πολύνεκρο πολεμικό γεγονός. Στη φωτογραία επεικονίζεται η Οικία Γεωργιουδάκη.",
  //     position: [35.51516, 24.03793],
  //     icon: "location_icon",
  //     image_source: " ",
  //   },
  //   {
  //     id: 16,
  //     name: "Ιερός Ναός Αγίας Μαρίας Μαγδαληνής",
  //     description: "",
  //     position: [35.5175, 24.03818],
  //     icon: "location_icon",
  //     image_source: " ",
  //   },
  //   {
  //     id: 17,
  //     name: "Αυτοδιαχειριζόμενο στέκι στη Χαλέπα",
  //     description: "",
  //     position: [35.518310, 24.037127],
  //     icon: "location_icon",
  //     image_source: " ",
  //   },
  // ];

const pois = [
    {
      id: 1,
      name: "Τα Ταμπακαριά της Χαλέπας",
      description: "Τα Ταμπακαριά της Χαλέπας μαζί με αυτά της Αγίας Κυριακής συναποτελούσαν τη σημαντικότερη βιομηχανική(για τα δεδομένα της Κρήτης) περιοχή των Χανίων και ίσως της Κρήτης, από τα μέσα του 19ου αιώνα έως και τη δεκαετία του 1970. Σήμερα, το τελευταίο εν λειτουργία βυρσοδεψείο του Χρήστου Φιλοΐτη στέκεται ακόμα σε πείσμα της των καιρών του αστικού εξευγενισμού και της παγκοσμιοποιημένης οικονομίας.  ",
      description_eng: "The Tabakaria of Halepa, together with those of Agia Kyriaki, formed the most important industrial area (by Cretan standards) of Chania and perhaps of Crete, from the mid-19th century until the 1970s. Today, the last operating tannery of Christos Filoitis still stands, defying the times of urban gentrification and the globalized economy.",
      position: [35.51982, 24.03845],
      icon: "location_icon",
      image_source: "image source: https://www.chania-heritage.gr/"
    },
    {
      id: 2,
      name: "Ελληνικό Προξενείο",
      description: "Στο σημείο αυτό, εκτός από την υπέροχη θέα προς το κέντρο της πόλης, μπορούμε να παρατηρήσουμε το Ελληνικό, το Βρετανικό και το Γερμανικό Προξενείο και η αφήγηση μας πυκνώνει για την ιστορία της Χαλέπας,  ως τόπος φιλοξενίας της διπλωματίας του ύστερου 19ου αιώνα. Ένα από τα πιο ιστορικά κτήρια της Χαλέπας, κτίσθηκε από τον βαμβακέμπορο Χορτάτζη τον 19ο αιώνα. ",
      description_eng: "From this spot, beyond the magnificent view toward the city center, one can observe the Greek, British, and German Consulates. The narrative thickens here around the history of Halepa as a hub of late 19th-century diplomacy. One of the most historic buildings in Halepa, it was built by the cotton merchant Hortatzis in the 19th century.",
      position: [35.51823571635969, 24.03572036417894],
      icon: "location_icon",
      image_source: "image source: ΚΛΑΔΟΥ-ΜΠΛΕΤΣΑ ΑΙΜΙΛΙΑ",
    },
    {
      id: 3,
      name: "Πρώην Γαλλική Σχολή",
      description: "Το υπέροχο και εκτεταμένο κτίριο της Γαλλικής σχολής, το οποίο έχει βιώσει αλλεπάλληλες αλλαγές χρήσεις, από ιδιωτική κατοικία Αιγύπτιου εμπόρου μέχρι την στέγαση  τη γαλλικής σχολής και της αρχιτεκτονικής σχολής του Πολυτεχνείου Κρήτης. ",
      description_eng: "The magnificent and expansive building of the French School has undergone successive changes of use, from the private residence of an Egyptian merchant to housing the French school and later the School of Architecture of the Technical University of Crete.",
      position: [35.51860, 24.03783],
      icon: "location_icon",
      image_source: "image source: ",
    },
    {
      id: 4,
      name: "Σπίτι Ελευθερίου Βενιζέλου",
      description: "Το σπίτι του Ελευθερίου Βενιζέλου, το οποίο σήμερα στεγάζει το Μουσείο Ελευθερίου Βενιζέλου, αποτελεί ένα από τα σημαντικότερα κτίρια της Χαλέπας και ένα από τα πιο σημαντικά ιστορικά κτίρια των Χανίων. Το σπίτι αυτό, το οποίο χτίστηκε στα τέλη του 19ου αιώνα, ήταν η κατοικία του Ελευθερίου Βενιζέλου, ενός από τους πιο σημαντικούς πολιτικούς της Ελλάδας και πρωθυπουργού της χώρας σε διάφορες περιόδους. Το σπίτι αυτό αποτελεί ένα σημαντικό μνημείο της ιστορίας της Ελλάδας και της Χαλέπας και είναι ένας δημοφιλής προορισμός για τους επισκέπτες που ενδιαφέρονται για την ιστορία και την πολιτική της χώρας.",
      description_eng: "The house of Eleftherios Venizelos, which today houses the Eleftherios Venizelos Museum, is one of the most important buildings in Halepa and one of the most significant historic buildings in Chania. Built in the late 19th century, it was the residence of Eleftherios Venizelos, one of Greece's most prominent politicians and prime minister during various periods. It is a significant monument of Greek and Halepa history and a popular destination for visitors interested in the country's history and politics.",
      position: [35.51835, 24.03869],
      icon: "location_icon",
      image_source: " ",
    },
    {
      id: 5,
      name: "Γαλλικό Προξενείο",
      description: "Το πρόσφατα ανακαινισμένο κτίριο του γάλλου προξένου Blanc μας προσφέρει τη δυνατότητα να αναλογιστούμε και να φανταστούμε τη μεγαλοπρεπή διάσταση του ανατολικού προαστείου των Χανίων, όπως αυτή είχε διαμορφωθεί προς τις τελευταίες δεκαετίες του 19ου αιώνα.",
      description_eng: "The recently renovated building of the French consul Blanc offers us the opportunity to reflect and imagine the grand dimension of the eastern suburb of Chania, as it had taken shape during the final decades of the 19th century.",
      position: [35.51763, 24.03995],
      icon: "location_icon",
      image_source: " ",
    },
    {
      id: 6,
      name: "Παλάτι Πρίγκιπα Γεωργίου",
      description: "Το Παλάτι του Πρίγκιπα Γεωργίου, το οποίο βρίσκεται στην περιοχή της Χαλέπας, αποτελεί ένα από τα σημαντικότερα ιστορικά κτίρια των Χανίων και ένα από τα πιο σημαντικά μνημεία της νεότερης ιστορίας της Ελλάδας. Το παλάτι αυτό χτίστηκε στα τέλη του 19ου αιώνα για τον Πρίγκιπα Γεώργιο, τον δεύτερο γιο του βασιλιά Γεωργίου Α' της Ελλάδας. Το παλάτι αυτό αποτελεί ένα σημαντικό μνημείο της ιστορίας της Ελλάδας και της Χαλέπας και είναι ένας δημοφιλής προορισμός για τους επισκέπτες που ενδιαφέρονται για την ιστορία και την αρχιτεκτονική της χώρας.",
      description_eng: "The Palace of Prince George, located in the Halepa area, is one of the most important historic buildings in Chania and one of the most significant monuments of modern Greek history. It was built in the late 19th century for Prince George, the second son of King George I of Greece. It is an important monument of Greek and Halepa history and a popular destination for visitors interested in the country's history and architecture.",
      position: [35.51865, 24.03831],
      icon: "location_icon",
      image_source: " ",
    },
    {
      id: 7,
      name: "Γερμανικό Προξενείο",
      description: "Το κτίριο που στέγαζε το γερμανικό προξενείο μέχρι και την περίοδο της Κρητικής Πολιτείας κατασκευάστηκε το 1870 από οθωμανό ανώτατο αξιωματούχο. Διέμενε στο κτίριο αυτό και ο Ρεούφ Πασάς των Χανίων, ο δημιουργός του Δημοτικού Κήπου.  Αποτέλεσε τη διπλωματική βάση όλων των μετεξελίξεων του γερμανικού κράτους, ακόμα και την περίοδο της ναζισμού. Κατά τη γερμανική κατοχή της Κρήτης στέγασε την γενική διοίκηση των κατοχών αρχών και φημολογείται ότι φιλοξένησε τον Έρβιν Ρόμμελ κατά την επιστροφή του από το βορειοαφρικανικό μέτωπο. ",
      description_eng: "The building that housed the German consulate until the period of the Cretan State was constructed in 1870 by a high-ranking Ottoman official. Reouf Pasha of Chania, the creator of the Municipal Garden, also resided here. It served as the diplomatic base through all transformations of the German state, even during the Nazi period. During the German occupation of Crete it housed the general administration of the occupying authorities, and it is rumored to have hosted Erwin Rommel upon his return from the North African front.",
      position: [35.51775, 24.0355],
      icon: "location_icon",
      image_source: " ",
    },
    {
      id: 8,
      name: "Βρετανικό Προξενείο",
      description: "",
      description_eng: "",
      position: [35.51789, 24.03618],
      icon: "location_icon",
      image_source: " ",
    },
    {
      id: 9,
      name: "Γερμανόφωνη καθολική εκκλησία",
      description: "",
      description_eng: "",
      position: [35.51786, 24.03915],
      icon: "location_icon",
      image_source: " ",
    },
    {
      id: 10,
      name: "Πλατεία Έλενα Βενιζέλου",
      description: "",
      description_eng: "",
      position: [35.51786, 24.03886],
      icon: "location_icon",
      image_source: " ",
    },
    {
      id: 11,
      name: "Εθνικό Ιδρυμα Ερευνών & Μελετών Ελευθέριος Βενιζέλος ",
      description: "Η πρώην οικία Μπλούμ κατασκευάστηκε στα μέσα του 19ου αιώνα από τον ομογενή έμπορο της Βεγγάζης, Εμμανουήλ Μπλούμ. Κατά την περίοδο της Κρητικής Πολιτείας στέγασε για λίγο το ιταλικό προξενείο, ενώ μετά τον θάνατο του Μπλούμ το 1911, μέρος της ιδιοκτησίας πέρασε στην ελληνική κοινότητα της Βεγγάζης, ώσπου το όλο συγκρότημα αγοράστηκε από το Ίδρυμα Βενιζέλος και το 2005 μετά από ανακαίνιση του κτιρίου στέγασε όλες τις λειτουργίες του ιδρύματος. ",
      description_eng: "The former Bloum residence was built in the mid-19th century by the Greek-diaspora merchant from Benghazi, Emmanuil Bloum. During the period of the Cretan State it briefly housed the Italian consulate, and after Bloum's death in 1911 part of the property passed to the Greek community of Benghazi, until the entire complex was purchased by the Venizelos Foundation. In 2005, following renovation, it came to house all of the foundation's operations.",
      position: [35.51796, 24.03888],
      icon: "location_icon",
      image_source: " ",
    },
    {
      id: 12,
      name: "Οικία Μαρκαντωνάκη",
      description: "Η Οικία της οικογένειας Μαρκαντωνάκη στη Χαλέπα Χανίων,κατασκευάστηκε αρχικά από τον αιγυπτιώτη Χορτάτζη το 1883. Ο Γεώργιος Χορτάτζης το κληροδότησε στην κόρη του Ερριέτα, η οποία παντρεύτηκε τον Πέτρο Μαρκαντωνάκη. Αποτελεί ιστορική βίλα της περιοχής, με ιδιαίτερη αρχιτεκτονική και με έναν υπέροχο κήπο. Το 1901, στο σπίτι αυτό κατοικούσε ο Γάλλος Συνταγματάρχης Émile Honoré Destelle.",
      description_eng: "The Markantoniakis family residence in Halepa, Chania was originally built by the Egyptian-Greek Hortatzis in 1883. Georgios Hortatzis bequeathed it to his daughter Errieta, who married Petros Markantoniakis. It is a historic villa of the area, with distinctive architecture and a magnificent garden. In 1901, the French Colonel Émile Honoré Destelle resided in this house.",
      position: [35.51691, 24.03946],
      icon: "location_icon",
      image_source: " ",
    },
    {
      id: 13,
      name: "Βίλλα Σβαρτς",
      description: "Η μεγαλόπρεπη αυτή βίλα με τους ιωνικούς κίονες ταυτίστηκε με την Ελπίδα Μέλαινα, η οποία την αγόρασε το 1875 και διέμεινε σε αυτήν εκεί μέχρι τα τέλη του 1880, όταν άφησε για πάντα την αγαπημένη της Χαλέπα, μετά από 20 χρόνια.  Μετέπειτα πέρασε στην ιδιοκτησία του γερμανού προξένου Ριχάρδου  Κρούγκερ, όπου και έμενε ο αδερφός του Μαξ. Τις τελευταίες δεκαετίες καταρρέει και οι ελπίδες να αναστηλωθεί ολοένα και λιγοστεύουν.  ",
      description_eng: "This magnificent villa with Ionic columns is associated with Elpida Melaina, who purchased it in 1875 and resided there until the late 1880s, when she left her beloved Halepa forever after 20 years. It later passed into the ownership of the German consul Richard Kruger, where his brother Max also lived. In recent decades it has been falling into ruin, and hopes for its restoration grow ever slimmer.",
      position: [35.51557, 24.03926],
      icon: "location_icon",
      image_source: " ",
    },
    {
      id: 14,
      name: "Οικία Βαλερίου Καλούτση",
      description: "Το νεοκλασικό αυτό διώροφο κτίριο κατασκευάστηκε  στις αρχές του 20ου αιώνα από τον Βαλέριο Καλούτση, τον μετέπειτα σύζυγο της Φλωρεντίνης Σκουλούδη- Καλούτση. Το πλούσιο σε διάκοσμο αυτό κτίριο φιλοξένησε μεγάλες προσωπικότητες της κρητικής κοινωνίας μέχρι να αποτελέσει από τα μέσα του 20ου αιώνα την κύρια κατοικία και εργαστήριο της Φλωρεντίνης. Γιος της Φλωρεντίνης ήταν ο σπουδαίος εικαστικός και ζωγράφος Βαλέριος Καλούτσης.",
      description_eng: "This neoclassical two-story building was constructed in the early 20th century by Valerios Kaloutsis, the future husband of Florentini Skouloudi-Kaloutsi. Richly decorated, it hosted prominent figures of Cretan society before becoming, from the mid-20th century, the primary residence and studio of Florentini. Her son was the distinguished visual artist and painter Valerios Kaloutsis.",
      position: [35.51606, 24.03855],
      icon: "location_icon",
      image_source: " ",
    },
    {
      id: 15,
      name: "Κατσαμπάς",
      description: "Μια ιστορική γωνιά της Χαλέπας, σταυροδρόμι συνοικιών και σημείο συνάντησης των Χανιωτών, όπου έζησαν σπουδαίες προσωπικότητες της πόλης μας, αλλά και συνδέθηκε με ένα ιδιαίτερο και πολύνεκρο πολεμικό γεγονός. Στη φωτογραία επεικονίζεται η Οικία Γεωργιουδάκη.",
      description_eng: "A historic corner of Halepa, a crossroads of neighborhoods and meeting point of the people of Chania, where great personalities of our city lived, and which is also linked to a particularly deadly wartime event. The photograph depicts the Georgioudakis Residence.",
      position: [35.51516, 24.03793],
      icon: "location_icon",
      image_source: " ",
    },
    {
      id: 16,
      name: "Ιερός Ναός Αγίας Μαρίας Μαγδαληνής",
      description: "",
      description_eng: "",
      position: [35.5175, 24.03818],
      icon: "location_icon",
      image_source: " ",
    },
    {
      id: 17,
      name: "Αυτοδιαχειριζόμενο στέκι στη Χαλέπα",
      description: "",
      description_eng: "",
      position: [35.518310, 24.037127],
      icon: "location_icon",
      image_source: " ",
    },
  ];

  export default pois;