const poisBak = [
    {
      id: 1,
      name: "Τα Ταμπακαριά της Χαλέπας",
      name_eng: "The Tanning Houses of Halepa",
      name_ger: "",
      name_fra: "",
      description: "Τα Ταμπακαριά της Χαλέπας μαζί με αυτά της Αγίας Κυριακής συναποτελούσαν τη σημαντικότερη βιομηχανική(για τα δεδομένα της Κρήτης) περιοχή των Χανίων και ίσως της Κρήτης, από τα μέσα του 19ου αιώνα έως και τη δεκαετία του 1970. Η ζώνη των βυρσοδεψείων γνώρισε τη μέγιστη ακμή της την περίοδο του μεσοπολέμου, καθώς λειτουργούσαν ταυτόχρονα μέχρι και 80 βιοτεχνικές μονάδες. Οι ταμπάκηδες, όπως ονομάζονταν οι εργάτες ζούσαν στην περιοχή της Χαλέπας και εκτός από δέρματα, παρήγαγαν και πολιτισμό, όπως για παράδειγμα η μουσική των Ταμπαχανιώτικων. Σήμερα, το τελευταίο εν λειτουργία βυρσοδεψείο του Χρήστου Φιλοΐτη στην κάτω Χαλέπα “στέκεται” ακόμα σε πείσμα  του αστικού εξευγενισμού και της παγκοσμιοποιημένης οικονομίας.",
      description_eng: "The Tanneries of Halepa, together with those of Agia Kyriaki, constituted the most important industrial area (by Cretan standards) of Chania and perhaps of Crete, from the mid-19th century until the 1970s. The tannery zone reached its peak during the interwar period, when as many as 80 workshop units operated simultaneously. The “Tampakides“, as the workers were called, lived in the Halepa area and, in addition to producing leather, also produced culture — for example, the music known as “Tabachaniotika”. Today, the last operating tannery, that of Christos Filoitis in lower Halepa, still “stands“ in defiance of urban gentrification and the globalized economy.",
      description_ger: "",
      description_fra: "",
      position: [35.51982, 24.03845],
      icon: "location_icon",
      className: "area",
      image_source: "https://www.chania-heritage.gr/",
      text_source:"",
    },
    {
      id: 2,
      name: "Το Ελληνικό Προξενείο",
      name_eng: "The Greek Consulate",
      description: "Κατασκευάστηκε από τον Γεώργιο Χορτάτζη, μεταξύ 1870-80 μεγαλέμπορο το οποίο χρησιμοποιήθηκε ως Ελληνικό προξενείο κατά την κρητική πολιτεία, αλλά και ως ιταλικό για ένα μικρό διάστημα. Σε αυτό έζησε κατά την ύστερη οθωμανική κυριαρχία ο Τζελαλεδίν Πασάς, ανώτατος στρατιωτικός διοικητής της Κρήτης. Η αναγεννησιακού ρυθμού πύλη του κήπου του εντυπωσιάζει τους περαστικούς, την οποία, όμως, δεν μπορεί κανείς να διαβεί, καθώς το κτίριο βρίσκεται εδώ και χρόνια σε μία παγωμένη διαδικασία ανακαίνισης, Λίγα χρόνια πριν κλείσει οριστικά, φιλοξένησε το κοσμικό κέντρο “Προξενείο”. ",
      description_eng: "Built by Georgios Hortatzis, a great merchant, between 1870–80, the building was used as the Greek Consulate during the Cretan State period, and briefly also as the Italian Consulate. During the late Ottoman rule, Celaleddin Pasha, the supreme military commander of Crete, lived here. The Renaissance-style garden gate impresses passersby, though no one can pass through it, as the building has been in a frozen state of renovation for years. A few years before it closed permanently, it housed the nightclub 'Proxenio' (The Consulate).",
      position: [35.51823571635969, 24.03572036417894],
      icon: "location_icon",
      className: "consulate",
      image_source: "image source: ΚΛΑΔΟΥ-ΜΠΛΕΤΣΑ ΑΙΜΙΛΙΑ",
    },
    {
      id: 3,
      name: "H Πρώην Γαλλική Σχολή",
      name_eng: "The Former French School",
      description: "Το υπέροχο και εκτεταμένο κτίριο της Γαλλικής σχολής, το οποίο έχει βιώσει αλλεπάλληλες αλλαγές χρήσεις, από ιδιωτική κατοικία Αιγύπτιου εμπόρου  τη δεκαετία του 1850 μέχρι την στέγαση  τη γαλλικής σχολής το 1895 από το ρωμαιοκαθολικό τάγμα των Αδελφών του Αγίου Ιωσήφ, οι οποίες και προσέθεσαν τις δύο πλαϊνές πτέρυγες. Λειτούργησε ως πρότυπο σχολείο πρωτοβάθμιας και δευτεροβάθμιας εκπαίδευσης μέχρι και το 1983, εστιάζοντας σε μεγάλο βαθμό στη διδασκαλία της γαλλικής γλώσσας αλλά και την εμφύσηση της γαλλικής κουλτούρας στις μαθήτριές του.  Εν  τέλει, από τα τέλη του 1970 πέρασε στο Υπουργείο Παιδείας  και για κάποια χρόνια στέγασε και την αρχιτεκτονική σχολή  του Πολυτεχνείου Κρήτης. ",
      description_eng: "The magnificent and extensive building of the French School has undergone successive changes of use, from the private residence of an Egyptian merchant in the 1850s to housing the French School in 1895, run by the Roman Catholic order of the Sisters of St. Joseph, who added the two side wings. It operated as a model school for primary and secondary education until 1983, focusing largely on teaching the French language and instilling French culture in its female students. Eventually, in the late 1970s, it passed into the hands of the Ministry of Education and for some years also housed the School of Architecture of the Technical University of Crete.",
      position: [35.51860, 24.03783],
      icon: "location_icon",
      className: "school",
      image_source: "image source: ",
    },
    {
      id: 4,
      name: "To Σπίτι του Ελευθερίου Βενιζέλου",
      name_eng: "The House of Eleftherios Venizelos",
      description: "Το σπίτι του Ελευθερίου Βενιζέλου, το οποίο σήμερα στεγάζει το Μουσείο Ελευθερίου Βενιζέλου, αποτελεί ένα από τα σημαντικότερα κτίρια της Χαλέπας .Το σπίτι αυτό, το οποίο χτίστηκε στα τέλη του 19ου αιώνα από τον πατέρα του Κυριάκο και ήταν η κύρια κατοικία του Ελευθερίου Βενιζέλου για μεγάλα χρονικά διαστήματα, ενός από τους πιο σημαντικούς πολιτικούς της Ελλάδας και πρωθυπουργού της χώρας. Η επίβλεψη της ανακαίνισής του  κτιρίου το 1927 έγινε από τον ίδιο τον Βενιζέλο, ενώ σήμερα αποτελεί επισκέψιμο μουσείο. Το σπίτι αυτό αποτελεί ένα σημαντικό μνημείο της ιστορίας της Ελλάδας και της Χαλέπας και είναι ένας δημοφιλής προορισμός για τους επισκέπτες που ενδιαφέρονται για την ιστορία και την πολιτική της χώρας.Μην παραμελήσετε να θαυμάσετε τον υπέροχο αμπελώνα στην ανατολική του πλευρά, τον μοναδικό αστικό αμπελώνα στην Ελλάδα. ",
      description_eng: "The house of Eleftherios Venizelos, which today houses the Eleftherios Venizelos Museum, is one of the most important buildings in Halepa and one of the most significant historic buildings in Chania. Built in the late 19th century, it was the residence of Eleftherios Venizelos, one of Greece's most prominent politicians and prime minister during various periods. It is a significant monument of Greek and Halepa history and a popular destination for visitors interested in the country's history and politics.",
      position: [35.51835, 24.03869],
      icon: "location_icon",
      className: "house",
      image_source: " ",
    },
    {
      id: 5,
      name: "Το Πρώην Γαλλικό Προξενείο (Domus Blanc)",
      name_eng: "The Former French Consulate (Domus Blanc)",
      description: "Το πρόσφατα ανακαινισμένο κτίριο του γάλλου προξένου Blanc μας προσφέρει τη δυνατότητα να αναλογιστούμε και να φανταστούμε τη μεγαλοπρεπή διάσταση του ανατολικού προαστείου των Χανίων, όπως αυτή είχε διαμορφωθεί προς τις τελευταίες δεκαετίες του 19ου αιώνα.Το κτίριο έχει μεγάλη ιστορία: θεμελιώθηκε το 1870 από τον μηχανικό Λεωνίδα Λυγκούνη, ο οποίος προικοδότησε με αυτό την κόρη του Ερασμία, όταν νυμφεύθηκε τον πρόξενο της Γαλλίας στην Κρήτη, Paul Blanc, ο οποίος έζησε στα χανιά από το  1886 to 1901. Με το φωτογραφικό του αρχείο κληροδότησε στις επόμενες γενιές πολύ σημαντικές εικόνες των Χανίων και ιδιαίτερα της Χαλέπας, σε μία εποχή που τα Χανιά βρίσκονταν στο επίκεντρο των γεωπολιτικών εξελίξεων. Για πολλές δεκαετίες, στο υπόγειο του κτιρίου, η σημαντική καλλιτέχνιδα της υφαντικής τέχνης Φλωρεντίνη Σκουλούδη- Καλούτση λειτουργούσε με τις μαθήτριές της γύρω στους 150 αργαλειούς, οι οποίοι αποτύπωναν τα μινωικά μοτίβα, καθιστώντας τα ανεξίτηλα στη συλλογική μνήμη και αισθητική των Κρητικών. ",
      description_eng: "The recently renovated building of the French consul Blanc offers us the opportunity to reflect upon and imagine the magnificent dimension of the eastern suburb of Chania, as it had been formed by the last decades of the 19th century. The building has a long history: it was founded in 1870 by the engineer Leonidas Lygkounis, who gave it as a dowry to his daughter Erasmia when she married Paul Blanc, the French Consul in Crete, who lived in Chania from 1886 to 1901. Through his photographic archive, he bequeathed to the following generations very important images of Chania and especially of Halepa, at a time when Chania was at the center of geopolitical developments. For many decades, in the basement of the building, the important weaving artist Florentini Skouloudi-Kaloutsi operated, with her students, around 150 looms that depicted Minoan motifs, making them indelible in the collective memory and aesthetics of the Cretans.",
      position: [35.51763, 24.03995],
      icon: "location_icon",
      className: "consulate",
      image_source: " ",
    },
    {
      id: 6,
      name: "To Παλάτι Πρίγκιπα Γεωργίου",
      name_eng: "The Palace of Prince George",
      description: "Το Παλάτι ή “Παλατάκι” λόγω του μικρού του μεγέθους,  του Πρίγκιπα Γεωργίου  χτίστηκε στα τέλη του 19ου αιώνα για λογαριασμό και αυτό του Θεμιστοκλή Μιτσοτάκη και λόγω της μεγαλοπρέπειά του, ήταν το ιδανικότερο κτίριο για να φιλοξενήσει τον Πρίγκιπα Γεώργιο, τον δεύτερο γιο του βασιλιά Γεωργίου Α' της Ελλάδας, όταν ο πρώτος ήρθε στα Χανιά το 1898, προκειμένου να διοικήσει ως Ύπατος Αρμοστής την Κρητική Πολιτεία (1898-1913). Η μεγαλόπρεπη αυλή του, καθώς και τα πολυτελή υλικά που χρησιμοποιήθηκαν για να την κατασκευή του, μαρτυρούν τις ένδοξες εποχές που “βίωσε’ αυτό το κτίσμα. Κατά την περίοδο της κατοχής, οι ναζί Γερμανοί το είχαν επιτάξει, όπως άλλωστε και τα περισσότερα πολυτελή κτίρια της Χαλέπας και στέγασαν εκεί το Στρατηγείο τους. ",
      description_eng: "The Palace of Prince George: The Palace, or 'Palataki' ('Little Palace') due to its small size, of Prince George was built at the end of the 19th century, also on behalf of Themistoklis Mitsotakis. Owing to its grandeur, it was the most ideal building to host Prince George, the second son of King George I of Greece, when the latter came to Chania in 1898 to govern the Cretan State as High Commissioner (1898–1913). Its magnificent courtyard, as well as the luxurious materials used in its construction, bear witness to the glorious eras this building 'experienced.' During the occupation, the Nazi Germans requisitioned it — as they did with most of Halepa's luxurious buildings — and housed their Headquarters there.",
      position: [35.51865, 24.03831],
      icon: "location_icon",
      className: "palace",
      image_source: " ",
    },
    {
      id: 7,
      name: "Γερμανικό Προξενείο",
      name_eng: "The German Consulate",
      description: "Το κτίριο που στέγαζε το γερμανικό προξενείο μέχρι και την περίοδο της Κρητικής Πολιτείας κατασκευάστηκε το 1870 από οθωμανό ανώτατο αξιωματούχο. Διέμενε στο κτίριο αυτό και ο Ρεούφ Πασάς των Χανίων, ο δημιουργός του Δημοτικού Κήπου.  Αποτέλεσε τη διπλωματική βάση του γερμανικού κράτους στα Χανιά, ακόμα και την περίοδο της ναζισμού. Κατά τη γερμανική κατοχή της Κρήτης στέγασε την Γενική διοίκηση των κατοχικών αρχών και φημολογείται ότι φιλοξένησε τον Έρβιν Ρόμελ κατά την επιστροφή του από το βορειο αφρικανικό μέτωπο.",
      description_eng: "The building that housed the German Consulate up until the period of the Cretan State was built in 1870 by a high-ranking Ottoman official. Reouf Pasha of Chania, the creator of the Municipal Garden, also lived in this building. It served as the diplomatic base of the German state in Chania, even during the Nazi era. During the German occupation of Crete, it housed the General Administration of the occupation authorities, and it is rumored to have hosted Erwin Rommel during his return from the North African front.",
      position: [35.51775, 24.0355],
      icon: "location_icon",
      className: "consulate",
      image_source: " ",
    },
    {
      id: 8,
      name: "Το Βρετανικό Προξενείο",
      name_eng: "The British Consulate",
      description: "Χτισμένο για λογαριασμό του Θεμιστοκλή Μητσοτάκη στα τέλη του 19ου αιώνα, το οποίο κληροδότησε στην κόρη του Φαιναρέτη. Σε αυτό διέμεινε ο πρίγκιπας Γεώργιος και πολλοί άλλοι πολιτικοί από τη δεκαετία του 1990 και μετά, αφότου μετατράπηκε σε ξενοδοχείο, καθώς πληρούσε εσωτερικά και εξωτερικά όλες τις προϋποθέσεις αισθητικής και μεγαλοπρέπειας. Φυσικά, για κάποια χρόνια, την περίοδο της Κρητικής Πολιτείας στέγασε και αυτό το πολυτελές κτίσμα το βρετανικό προξενείο, με το οποίο έχει ταυτιστεί από την κοινωνία της Χαλέπας.",
      description_eng: "Built on behalf of Themistoklis Mitsotakis at the end of the 19th century, who bequeathed it to his daughter Phenarete. Prince George stayed here, as did many other politicians from the 1990s onward, after it was converted into a hotel, since it met all the aesthetic and grandeur requirements both internally and externally. Naturally, for some years during the period of the Cretan State, this luxurious building also housed the British Consulate, with which it has been identified by the community of Halepa.",
      position: [35.51789, 24.03618],
      icon: "location_icon",
      className: "consulate",
      image_source: " ",
    },
    {
      id: 9,
      name: "H Γερμανόφωνη καθολική εκκλησία",
      name_eng: "The German-speaking Catholic Church",
      description: "",
      description_eng: "",
      position: [35.51786, 24.03915],
      icon: "location_icon",
      className: "church",
      image_source: " ",
    },
    {
      id: 10,
      name: "Πλατεία Έλενα Βενιζέλου",
      description: "",
      description_eng: "",
      position: [35.51786, 24.03875],
      icon: "location_icon",
      className: "square",
      image_source: " ",
    },
    {
      id: 11,
      name: "Εθνικό Ιδρυμα Ερευνών & Μελετών 'Ελευθέριος Βενιζέλος'",
      name_eng: "National Research & Studies Foundation 'Eleftherios Venizelos'",
      description: "Η πρώην οικία Μπλούμ κατασκευάστηκε στα μέσα του 19ου αιώνα από τον ομογενή έμπορο της Βεγγάζης, Εμμανουήλ Μπλούμ. Κατά την περίοδο της Κρητικής Πολιτείας στέγασε για λίγο καιρό το ιταλικό προξενείο, ενώ μετά τον θάνατο του Μπλούμ το 1911, μέρος της ιδιοκτησίας πέρασε στην ελληνική κοινότητα της Βεγγάζης, ώσπου το όλο συγκρότημα αγοράστηκε από το Ίδρυμα Βενιζέλος και από το 2005 μετά από ανακαίνιση του κτιρίου στέγασε όλες τις λειτουργίες του ιδρύματος. ",
      description_eng: "The former Bloum residence was built in the mid-19th century by Emmanuel Bloum, a diaspora merchant from Benghazi. During the period of the Cretan State, it briefly housed the Italian Consulate, and after Bloum's death in 1911, part of the property passed to the Greek community of Benghazi, until the entire complex was purchased by the Venizelos Foundation. Since 2005, following renovation, the building has housed all the foundation's functions.",
      position: [35.518, 24.03888],
      icon: "location_icon",
      className: "institution",
      image_source: " ",
    },
    {
      id: 12,
      name: "Οικία Μαρκαντωνάκη",
      name_eng: "The Markantonakis Residence",
      description: "Η Οικία της οικογένειας Μαρκαντωνάκη στη Χαλέπα Χανίων,κατασκευάστηκε αρχικά και αυτή από τον Λεωνίδα Λυγκούνη το 1883. Ο Λυγκούνης το κληροδότησε στην κόρη του Ερριέτα, η οποία παντρεύτηκε τον Πέτρο Μαρκαντωνάκη και έτσι έμεινε στην ιστορία της πόλης ως η οικία Μαρκαντωνάκη. Αποτελεί ιστορική βίλα της περιοχής, με ιδιαίτερη αρχιτεκτονική και με έναν υπέροχο κήπο με εντυπωσιακές αροκάριες. Το 1901, στο σπίτι αυτό διέμενε για ένα διάστημα ο Γάλλος Συνταγματάρχης Émile Honoré Destelle, ο οποίος και απεικονίζεται στο φωτογραφικό στιγμιότυπο. Σήμερα, αποτελεί ιδιωτική κατοικία. ",
      description_eng: "The home of the Markantonakis family in Halepa, Chania, was also originally built by Leonidas Lygkounis in 1883. Lygkounis bequeathed it to his daughter Errieta, who married Petros Markantonakis — and so it has remained in the city's history as the Markantonakis Residence. It is a historic villa of the area, with distinctive architecture and a wonderful garden featuring impressive araucaria trees. In 1901, the French Colonel Émile Honoré Destelle stayed in this house for a time and is depicted in the photographic snapshot. Today, it is a private residence.",
      position: [35.51691, 24.03946],
      icon: "location_icon",
      className: "house",
      image_source: " ",
    },
    {
      id: 13,
      name: "Βίλλα Σβαρτς",
      name_eng: "Villa Swartz",
      description: "Η μεγαλόπρεπης αυτή βίλα με τους ιωνικούς κίονες ταυτίστηκε με την Ελπίδα Μέλαινα, Marie Espérance von Schwartz, η οποία την αγόρασε το 1875 και διέμεινε σε αυτήν εκεί μέχρι τα τέλη του 1880, όταν άφησε για πάντα την αγαπημένη της Χαλέπα, μετά από 20 χρόνια σχεδόν συνεχής κατοίκησης. Συγγραφέας, περιηγήτρια, φιλοκρήσσα και γαριβαλδινή, η Ελπίδα Μέλαινα αγάπησε τη Χαλέπα και στήριξε με ανιδιοτέλεια τους κρητικούς αγωνιστές κατά την επανάσταση του 1866-67 και φρόντισε για πολλά χρόνια τα αδέσποτα ζώα της πόλη μας.  Μετέπειτα, η βίλλα πέρασε στην ιδιοκτησία του γερμανού προξένου Ριχάρδου  Κρούγκερ, όπου και διέμενε σε αυτή ο μυστηριώδης και ντυμένος πάντα στα λευκά αδερφός του Μαξ. Στα υπόγειά του, την περίοδο της γερμανικής κατοχής, πολλοί Χανιώτες φυλακίστηκαν για μικρά διαστήματα από τους ναζιστές γερμανούς. Τις τελευταίες δεκαετίες το κτίριο  καταρρέει και οι ελπίδες να αναστηλωθεί ολοένα και λιγοστεύουν, παρά το γεγονός ότι έχει χαρακτηριστεί διατηρητέο.",
      description_eng: "Villa Schwartz: This magnificent villa with Ionic columns is identified with Elpida Melaina (Marie Espérance von Schwartz), who bought it in 1875 and lived there until the late 1880s, when she left her beloved Halepa forever after almost 20 years of continuous residence. A writer, traveler, philhellene, and Garibaldian, Elpida Melaina loved Halepa and selflessly supported the Cretan fighters during the revolution of 1866–67, and for many years cared for the stray animals of our city. Later, the villa passed into the ownership of the German Consul Richard Krüger, where his mysterious brother Max — who was always dressed in white — also lived. In its basement, during the German occupation, many residents of Chania were imprisoned for short periods by the Nazi Germans. In recent decades the building has been falling into ruin, and the hopes of restoring it are dwindling, despite the fact that it has been designated as a listed building.",
      position: [35.51557, 24.03926],
      icon: "location_icon",
      className: "house",
      image_source: " ",
    },
    {
      id: 14,
      name: "Οικία Βαλερίου Καλούτση",
      name_eng: "Valerios Kaloutsis Residence",
      description: "Το νεοκλασικό αυτό διώροφο κτίριο κατασκευάστηκε  στις αρχές του 20ου αιώνα από τον Βαλέριο Καλούτση, τον μετέπειτα σύζυγο της Φλωρεντίνης Σκουλούδη- Καλούτση. Το πλούσιο σε διάκοσμο αυτό κτίριο φιλοξένησε μεγάλες προσωπικότητες της κρητικής κοινωνίας μέχρι να αποτελέσει από τα μέσα του 20ου αιώνα την κύρια κατοικία και εργαστήριο της Φλωρεντίνης. Γιος της Φλωρεντίνης ήταν ο σπουδαίος εικαστικός και ζωγράφος Βαλέριος Καλούτσης. Η Φλωρεντίνη Καλούτση, εκτός του ότι αναβίωσε την μινωική αισθητική και τέχνη στα χειροποίητα υφαντά του εργαστηρίου της, έδωσε τη δυνατότητα σε Χανιώτισσες αφενός να εργαστούν και αφετέρου να βιώσουν τα πρώτα ψήγματα της γυναικείας  χειραφέτησης.",
      description_eng: "This neoclassical two-story building was constructed in the early 20th century by Valerios Kaloutsis, the future husband of Florentini Skouloudi-Kaloutsi. Richly decorated, this building hosted great personalities of Cretan society until, from the mid-20th century onward, it became Florentini's main residence and workshop. Florentini's son was the great visual artist and painter Valerios Kaloutsis. Florentini Kaloutsi, in addition to reviving Minoan aesthetics and art in the handmade textiles of her workshop, gave the women of Chania the opportunity both to work and to experience the first glimmers of female emancipation.",
      position: [35.51606, 24.03855],
      icon: "location_icon",
      className: "house",
      image_source: " ",
    },
    {
      id: 15,
      name: "Κατσαμπάς",
      name_eng: "Katsampas",
      description: "Μια ιστορική γωνιά της Χαλέπας, σταυροδρόμι συνοικιών και σημείο συνάντησης των Χανιωτών,όπου κατοικούσαν σπουδαίες  προσωπικότητες της πόλης μας, αλλά και συνδέθηκε με ένα ιδιαίτερο και πολύνεκρο πολεμικό γεγονός. Τον Σεπτέμβριο του 1942, ένα βρετανικό αεροσκάφος, βαλλόμενο από γερμανικά αντιαεροπορικά έριψε για άγνωστο λόγο (μία θεωρία είναι ότι ήθελε να πλήξει τα στρατιωτικά οχήματα των Γερμανών που ήταν σταθμευμένα στον κήπο της Αγίας Μαγδαληνής) τις βόμβες που μετέφερε στην πλατεία του Κατσαμπά, με αποτέλεσμα να σκοτωθούν πάνω από 30 άμαχοι, οι οποίοι βρίσκονταν εκείνη της στιγμή στα παρακείμενα εμπορικά καταστήματα. Μία από τα σοβαρότερα αεροπορικά πλήγματα στην πόλη των Χανίων, μακριά από το κέντρο της πόλης.  ",
      description_eng: "A historic corner of Halepa, a crossroads of neighborhoods and a meeting point for the people of Chania, where many distinguished personalities of our city lived — but also a place linked to a particular and deadly wartime event. In September 1942, a British aircraft, under fire from German anti-aircraft guns, dropped — for unknown reasons (one theory is that it intended to strike the German military vehicles parked in the garden of Agia Magdalini) — the bombs it was carrying onto the square of Katsambas, resulting in the deaths of more than 30 civilians who were at that moment in the surrounding shops. It was one of the most serious aerial strikes on the city of Chania, far from the city center.",
      position: [35.51516, 24.03793],
      icon: "location_icon",
      className: "area",
      image_source: " ",
    },
    {
      id: 16,
      name: "O Ιερός Ναός Αγίας Μαρίας Μαγδαληνής",
      name_eng: "The Holy Church of St. Mary Magdalene",
      description: "Η εκκλησία της Αγίας Μαρίας της Μαγδαληνής, ο λεγόμενος «ηγεμονικός ναός», κτίστηκε, όταν ο Ύπατος Αρμοστής (Ηγεμόνας) της Κρήτης Πρίγκιπας Γεώργιος, του οποίου η μητέρα ήταν η Όλγα, ρωσίδα και Βασίλισσα των Ελλήνων, προσέφερε στις αρχές του 1901 δέκα χιλιάδες ρούβλια και τα σχέδια για την ανέγερση μιας εκκλησίας, σε ανάμνηση της διαμονής στα Χανιά της αδελφής του Μαρίας, συζύγου του Μεγάλου Δούκα της Ρωσίας Γεωργίου. (πηγή 3) Έχει έντονες και σαφείς αρχιτεκτονικές επιρροές από την παραδοσιακή ρωσική ναοδομία, ιδιαίτερα εμφανείς στο τμήμα του τρούλου. Στο ναό αυτό μεταφέρθηκε η σορός του Ελευθερίου Βενιζέλου, προκειμένου να τεθεί προς λαϊκό προσκύνημα, ενώ ο κήπος του χρησιμοποιήθηκε από τον γερμανικό στρατό ως όρχος στρατιωτικών οχημάτων κατά την περίοδο της ναζιστικής κατοχής (1941-1945). ",
      description_eng: "The church of St. Mary Magdalene, the so-called 'princely church,' was built when the High Commissioner (Hegemon) of Crete, Prince George — whose mother was Olga, a Russian and Queen of the Hellenes — offered, in early 1901, ten thousand rubles and the plans for the construction of a church, in commemoration of the stay in Chania of his sister Maria, wife of Grand Duke George of Russia. (source 3) It bears strong and clear architectural influences from traditional Russian church architecture, particularly visible in the dome. The body of Eleftherios Venizelos was brought to this church to lie in state for public veneration, while its garden was used by the German army as a depot for military vehicles during the Nazi occupation (1941–1945).",
      position: [35.5175, 24.03818],
      icon: "location_icon",
      className: "church",
      image_source: " ",
    },
    {
      id: 17,
      name: "To Αυτοδιαχειριζόμενο Στέκι στη Χαλέπα",
      name_eng: "The Self-Managed Social Center of Chania ",
      description: "Άλλο ένα τοπόσημο της σύγχρονης ιστορία της Χαλέπας ήταν και το Αυτοδιαχειριζόμενο Στέκι Χανίων. Για δέκα χρόνια, από το 1996 μέχρι το 2006 στεγάστηκε στο κτίριο αυτό η πρώτη συλλογικότητα οριζόντιας συνέλευσης στα Χανιά, η οποία δραστηριοποιήθηκε σε ζητήματα πολιτικά, οικολογικά και συνδικαλιστικά, παρεμβαίνοντας δυναμικά και με πολιτικά προτάγματα σε όλη την Κρήτη, όπου αυτό κρινόταν απαραίτητο από το μοναδικό της πολιτικό όργανο, την εβδομαδιαία της συνέλευση. Το “Μαύρο Ρίφι” ήταν για χρόνια το περιοδικό του έντυπο. ",
      description_eng: "Another landmark of Halepa's modern history was the Self-Managed Social Center of Chania. For ten years, from 1996 to 2006, this building housed the first horizontal-assembly collective in Chania, which was active on political, ecological, and union issues, intervening dynamically and with political agendas throughout Crete wherever this was deemed necessary by its sole political body — its weekly assembly. 'Mavro Rifi' (Black Reef) was for years its printed magazine. ",
      position: [35.518310, 24.037127],
      icon: "location_icon",
      className: "house",
      image_source: " ",
    },
  ];

  const pois = [
  {
      id: 1,
      name: "Τα Ταμπακαριά της Χαλέπας",
      name_eng: "The Tanning Houses of Halepa",
      name_ger: "Die Gerbereien von Halepa",
      name_fra: "Les Tanneries de Halépa",
      description: "Τα Ταμπακαριά της Χαλέπας μαζί με αυτά της Αγίας Κυριακής συναποτελούσαν τη σημαντικότερη βιομηχανική(για τα δεδομένα της Κρήτης) περιοχή των Χανίων και ίσως της Κρήτης, από τα μέσα του 19ου αιώνα έως και τη δεκαετία του 1970. Η ζώνη των βυρσοδεψείων γνώρισε τη μέγιστη ακμή της την περίοδο του μεσοπολέμου, καθώς λειτουργούσαν ταυτόχρονα μέχρι και 80 βιοτεχνικές μονάδες. Οι ταμπάκηδες, όπως ονομάζονταν οι εργάτες ζούσαν στην περιοχή της Χαλέπας και εκτός από δέρματα, παρήγαγαν και πολιτισμό, όπως για παράδειγμα η μουσική των Ταμπαχανιώτικων. Σήμερα, το τελευταίο εν λειτουργία βυρσοδεψείο του Χρήστου Φιλοΐτη στην κάτω Χαλέπα 'στέκεται' ακόμα σε πείσμα  του αστικού εξευγενισμού και της παγκοσμιοποιημένης οικονομίας.",
      description_eng: "The Tanneries of Halepa, together with those of Agia Kyriaki, constituted the most important industrial area (by Cretan standards) of Chania and perhaps of Crete, from the mid-19th century until the 1970s. The tannery zone reached its peak during the interwar period, when as many as 80 workshop units operated simultaneously. The 'Tampakides', as the workers were called, lived in the Halepa area and, in addition to producing leather, also produced culture — for example, the music known as 'Tabachaniotika'. Today, the last operating tannery, that of Christos Filoitis in lower Halepa, still 'stands' in defiance of urban gentrification and the globalized economy.",
      description_ger: "Die Gerbereien von Halepa bildeten zusammen mit jenen von Agia Kyriaki das bedeutendste Industriegebiet (gemessen an kretischen Verhältnissen) von Chania und vielleicht ganz Kretas, von der Mitte des 19. Jahrhunderts bis in die 1970er Jahre. Die Gerbereizone erlebte ihren Höhepunkt in der Zwischenkriegszeit, als gleichzeitig bis zu 80 Handwerksbetriebe in Betrieb waren. Die sogenannten 'Tampakides', wie die Arbeiter genannt wurden, lebten im Viertel Halepa und produzierten neben Leder auch Kultur — zum Beispiel die als 'Tabachaniotika' bekannte Musik. Heute steht die letzte noch in Betrieb befindliche Gerberei, die von Christos Filoitis in Unter-Halepa, noch immer trotz Gentrifizierung und globalisierter Wirtschaft.",
      description_fra: "Les tanneries de Halépa, avec celles d'Agia Kyriaki, constituaient la zone industrielle la plus importante (à l'échelle crétoise) de La Canée et peut-être de toute la Crète, depuis le milieu du XIXe siècle jusqu'aux années 1970. La zone des tanneries connut son apogée pendant l'entre-deux-guerres, lorsque jusqu'à 80 unités artisanales fonctionnaient simultanément. Les « Tampakides », comme on appelait les ouvriers, vivaient dans le quartier de Halépa et, en plus du cuir, produisaient aussi de la culture — par exemple la musique connue sous le nom de « Tabachaniotika ». Aujourd'hui, la dernière tannerie encore en activité, celle de Christos Filoitis dans le bas-Halépa, tient encore debout malgré la gentrification urbaine et l'économie mondialisée.",
      position: [35.51982, 24.03845],
      icon: "location_icon",
      className: "area",
      image_source: "https://www.chania-heritage.gr/",
      text_source:"",
    },
    {
      id: 2,
      name: "Το Ελληνικό Προξενείο",
      name_eng: "The Greek Consulate",
      name_ger: "Das Griechische Konsulat",
      name_fra: "Le Consulat Grec",
      description: "Κατασκευάστηκε από τον Γεώργιο Χορτάτζη, μεταξύ 1870-80 μεγαλέμπορο το οποίο χρησιμοποιήθηκε ως Ελληνικό προξενείο κατά την κρητική πολιτεία, αλλά και ως ιταλικό για ένα μικρό διάστημα. Σε αυτό έζησε κατά την ύστερη οθωμανική κυριαρχία ο Τζελαλεδίν Πασάς, ανώτατος στρατιωτικός διοικητής της Κρήτης. Η αναγεννησιακού ρυθμού πύλη του κήπου του εντυπωσιάζει τους περαστικούς, την οποία, όμως, δεν μπορεί κανείς να διαβεί, καθώς το κτίριο βρίσκεται εδώ και χρόνια σε μία παγωμένη διαδικασία ανακαίνισης, Λίγα χρόνια πριν κλείσει οριστικά, φιλοξένησε το κοσμικό κέντρο 'Προξενείο'.",
      description_eng: "Built by Georgios Hortatzis, a great merchant, between 1870–80, the building was used as the Greek Consulate during the Cretan State period, and briefly also as the Italian Consulate. During the late Ottoman rule, Celaleddin Pasha, the supreme military commander of Crete, lived here. The Renaissance-style garden gate impresses passersby, though no one can pass through it, as the building has been in a frozen state of renovation for years. A few years before it closed permanently, it housed the nightclub 'Proxenio' (The Consulate).",
      description_ger: "Das Gebäude wurde zwischen 1870 und 1880 vom Großkaufmann Georgios Hortatzis erbaut und diente während der Kretischen Republik als griechisches Konsulat sowie kurzzeitig auch als italienisches Konsulat. Während der späten osmanischen Herrschaft lebte hier Celaleddin Pascha, der oberste Militärbefehlshaber Kretas. Das renaissancezeitliche Gartentor beeindruckt die Passanten, doch kann es niemand durchschreiten, da sich das Gebäude seit Jahren in einem eingefrorenen Renovierungszustand befindet. Einige Jahre vor seiner endgültigen Schließung beherbergte es den Nachtclub 'Proxenio' (Das Konsulat).",
      description_fra: "Construit par Georgios Hortatzis, grand négociant, entre 1870 et 1880, le bâtiment fut utilisé comme consulat grec durant la période de l'État crétois, et brièvement aussi comme consulat italien. Sous la domination ottomane tardive, Celaleddin Pacha, commandant militaire suprême de Crète, y résida. Le portail du jardin de style Renaissance impressionne les passants, mais nul ne peut le franchir, car le bâtiment est depuis des années dans un état de rénovation figé. Quelques années avant sa fermeture définitive, il accueillit la boîte de nuit « Proxenio » (Le Consulat).",
      position: [35.51823571635969, 24.03572036417894],
      icon: "location_icon",
      className: "consulate",
      image_source: "image source: ΚΛΑΔΟΥ-ΜΠΛΕΤΣΑ ΑΙΜΙΛΙΑ",
    },
    {
      id: 3,
      name: "H Πρώην Γαλλική Σχολή",
      name_eng: "The Former French School",
      name_ger: "Die Ehemalige Französische Schule",
      name_fra: "L'Ancienne École Française",
      description: "Το υπέροχο και εκτεταμένο κτίριο της Γαλλικής σχολής, το οποίο έχει βιώσει αλλεπάλληλες αλλαγές χρήσεις, από ιδιωτική κατοικία Αιγύπτιου εμπόρου  τη δεκαετία του 1850 μέχρι την στέγαση  τη γαλλικής σχολής το 1895 από το ρωμαιοκαθολικό τάγμα των Αδελφών του Αγίου Ιωσήφ, οι οποίες και προσέθεσαν τις δύο πλαϊνές πτέρυγες. Λειτούργησε ως πρότυπο σχολείο πρωτοβάθμιας και δευτεροβάθμιας εκπαίδευσης μέχρι και το 1983, εστιάζοντας σε μεγάλο βαθμό στη διδασκαλία της γαλλικής γλώσσας αλλά και την εμφύσηση της γαλλικής κουλτούρας στις μαθήτριές του.  Εν  τέλει, από τα τέλη του 1970 πέρασε στο Υπουργείο Παιδείας  και για κάποια χρόνια στέγασε και την αρχιτεκτονική σχολή  του Πολυτεχνείου Κρήτης. ",
      description_eng: "The magnificent and extensive building of the French School has undergone successive changes of use, from the private residence of an Egyptian merchant in the 1850s to housing the French School in 1895, run by the Roman Catholic order of the Sisters of St. Joseph, who added the two side wings. It operated as a model school for primary and secondary education until 1983, focusing largely on teaching the French language and instilling French culture in its female students. Eventually, in the late 1970s, it passed into the hands of the Ministry of Education and for some years also housed the School of Architecture of the Technical University of Crete.",
      description_ger: "Das prächtige und weitläufige Gebäude der Französischen Schule hat aufeinanderfolgende Nutzungsänderungen erlebt — von der Privatresidenz eines ägyptischen Kaufmanns in den 1850er Jahren bis zur Beherbergung der Französischen Schule ab 1895 durch den römisch-katholischen Orden der Schwestern des Heiligen Josef, die die beiden Seitenflügel hinzufügten. Es fungierte bis 1983 als Musterschule für die Primar- und Sekundarbildung und legte dabei großen Wert auf den Französischunterricht sowie die Vermittlung französischer Kultur an seine Schülerinnen. Ende der 1970er Jahre ging es schließlich an das Bildungsministerium über und beherbergte für einige Jahre auch die Architekturfakultät der Technischen Universität Kreta.",
      description_fra: "Le magnifique et vaste bâtiment de l'École française a connu des changements d'usage successifs — de la résidence privée d'un marchand égyptien dans les années 1850 à l'accueil de l'École française en 1895, gérée par l'ordre catholique des Sœurs de Saint-Joseph, qui ajoutèrent les deux ailes latérales. Il fonctionna comme école modèle d'enseignement primaire et secondaire jusqu'en 1983, en se consacrant largement à l'enseignement de la langue française et à l'inculcation de la culture française à ses élèves. À la fin des années 1970, il passa entre les mains du ministère de l'Éducation et accueillit pendant quelques années l'École d'Architecture de l'Université Polytechnique de Crète.",
      position: [35.51860, 24.03783],
      icon: "location_icon",
      className: "school",
      image_source: "image source: ",
    },
    {
      id: 4,
      name: "To Σπίτι του Ελευθερίου Βενιζέλου",
      name_eng: "The House of Eleftherios Venizelos",
      name_ger: "Das Haus von Eleftherios Venizelos",
      name_fra: "La Maison d'Eleftherios Venizelos",
      description: "Το σπίτι του Ελευθερίου Βενιζέλου, το οποίο σήμερα στεγάζει το Μουσείο Ελευθερίου Βενιζέλου, αποτελεί ένα από τα σημαντικότερα κτίρια της Χαλέπας .Το σπίτι αυτό, το οποίο χτίστηκε στα τέλη του 19ου αιώνα από τον πατέρα του Κυριάκο και ήταν η κύρια κατοικία του Ελευθερίου Βενιζέλου για μεγάλα χρονικά διαστήματα, ενός από τους πιο σημαντικούς πολιτικούς της Ελλάδας και πρωθυπουργού της χώρας. Η επίβλεψη της ανακαίνισής του  κτιρίου το 1927 έγινε από τον ίδιο τον Βενιζέλο, ενώ σήμερα αποτελεί επισκέψιμο μουσείο. Το σπίτι αυτό αποτελεί ένα σημαντικό μνημείο της ιστορίας της Ελλάδας και της Χαλέπας και είναι ένας δημοφιλής προορισμός για τους επισκέπτες που ενδιαφέρονται για την ιστορία και την πολιτική της χώρας.Μην παραμελήσετε να θαυμάσετε τον υπέροχο αμπελώνα στην ανατολική του πλευρά, τον μοναδικό αστικό αμπελώνα στην Ελλάδα. ",
      description_eng: "The house of Eleftherios Venizelos, which today houses the Eleftherios Venizelos Museum, is one of the most important buildings in Halepa and one of the most significant historic buildings in Chania. Built in the late 19th century, it was the residence of Eleftherios Venizelos, one of Greece's most prominent politicians and prime minister during various periods. It is a significant monument of Greek and Halepa history and a popular destination for visitors interested in the country's history and politics.",
      description_ger: "Das Haus von Eleftherios Venizelos, in dem heute das Eleftherios-Venizelos-Museum untergebracht ist, ist eines der bedeutendsten Gebäude in Halepa und eines der wichtigsten historischen Gebäude von Chania. Es wurde Ende des 19. Jahrhunderts von seinem Vater Kyriakos erbaut und war über lange Zeiträume die Hauptresidenz von Eleftherios Venizelos, einem der bedeutendsten Politiker und Ministerpräsidenten Griechenlands. Die Renovierungsarbeiten von 1927 wurden von Venizelos persönlich beaufsichtigt. Das Haus ist ein wichtiges Denkmal der griechischen Geschichte und ein beliebtes Ziel für Besucher, die sich für die Geschichte und Politik des Landes interessieren. Versäumen Sie nicht, den wunderbaren Weinberg auf der Ostseite zu bewundern — den einzigen städtischen Weinberg Griechenlands.",
      description_fra: "La maison d'Eleftherios Venizelos, qui abrite aujourd'hui le musée Eleftherios Venizelos, est l'un des bâtiments les plus importants de Halépa et l'un des monuments historiques les plus significatifs de La Canée. Construite à la fin du XIXe siècle par son père Kyriakos, elle fut la résidence principale d'Eleftherios Venizelos, l'un des hommes politiques les plus éminents de Grèce et Premier ministre du pays à plusieurs reprises. La rénovation de 1927 fut supervisée par Venizelos lui-même. C'est un monument important de l'histoire grecque et une destination prisée des visiteurs intéressés par l'histoire et la politique du pays. Ne manquez pas d'admirer le magnifique vignoble sur sa façade est — le seul vignoble urbain de Grèce.",
      position: [35.51835, 24.03869],
      icon: "location_icon",
      className: "house",
      image_source: " ",
    },
    {
      id: 5,
      name: "Το Πρώην Γαλλικό Προξενείο (Domus Blanc)",
      name_eng: "The Former French Consulate (Domus Blanc)",
      name_ger: "Das Ehemalige Französische Konsulat (Domus Blanc)",
      name_fra: "L'Ancien Consulat Français (Domus Blanc)",
      description: "Το πρόσφατα ανακαινισμένο κτίριο του γάλλου προξένου Blanc μας προσφέρει τη δυνατότητα να αναλογιστούμε και να φανταστούμε τη μεγαλοπρεπή διάσταση του ανατολικού προαστείου των Χανίων, όπως αυτή είχε διαμορφωθεί προς τις τελευταίες δεκαετίες του 19ου αιώνα.Το κτίριο έχει μεγάλη ιστορία: θεμελιώθηκε το 1870 από τον μηχανικό Λεωνίδα Λυγκούνη, ο οποίος προικοδότησε με αυτό την κόρη του Ερασμία, όταν νυμφεύθηκε τον πρόξενο της Γαλλίας στην Κρήτη, Paul Blanc, ο οποίος έζησε στα χανιά από το  1886 to 1901. Με το φωτογραφικό του αρχείο κληροδότησε στις επόμενες γενιές πολύ σημαντικές εικόνες των Χανίων και ιδιαίτερα της Χαλέπας, σε μία εποχή που τα Χανιά βρίσκονταν στο επίκεντρο των γεωπολιτικών εξελίξεων. Για πολλές δεκαετίες, στο υπόγειο του κτιρίου, η σημαντική καλλιτέχνιδα της υφαντικής τέχνης Φλωρεντίνη Σκουλούδη- Καλούτση λειτουργούσε με τις μαθήτριές της γύρω στους 150 αργαλειούς, οι οποίοι αποτύπωναν τα μινωικά μοτίβα, καθιστώντας τα ανεξίτηλα στη συλλογική μνήμη και αισθητική των Κρητικών. ",
      description_eng: "The recently renovated building of the French consul Blanc offers us the opportunity to reflect upon and imagine the magnificent dimension of the eastern suburb of Chania, as it had been formed by the last decades of the 19th century. The building has a long history: it was founded in 1870 by the engineer Leonidas Lygkounis, who gave it as a dowry to his daughter Erasmia when she married Paul Blanc, the French Consul in Crete, who lived in Chania from 1886 to 1901. Through his photographic archive, he bequeathed to the following generations very important images of Chania and especially of Halepa, at a time when Chania was at the center of geopolitical developments. For many decades, in the basement of the building, the important weaving artist Florentini Skouloudi-Kaloutsi operated, with her students, around 150 looms that depicted Minoan motifs, making them indelible in the collective memory and aesthetics of the Cretans.",
      description_ger: "Das kürzlich renovierte Gebäude des französischen Konsuls Blanc bietet uns die Möglichkeit, über die prachtvolle Dimension des östlichen Vororts von Chania nachzudenken und sie sich vorzustellen, wie sie sich in den letzten Jahrzehnten des 19. Jahrhunderts herausgebildet hatte. Das Gebäude hat eine lange Geschichte: Es wurde 1870 vom Ingenieur Leonidas Lygkounis gegründet, der es seiner Tochter Erasmia als Mitgift gab, als sie Paul Blanc, den französischen Konsul auf Kreta, heiratete, der von 1886 bis 1901 in Chania lebte. Durch sein Fotoarchiv hinterließ er den folgenden Generationen sehr wichtige Bilder von Chania und insbesondere von Halepa, zu einer Zeit, als Chania im Mittelpunkt geopolitischer Entwicklungen stand. Über viele Jahrzehnte betrieb die bedeutende Webkünstlerin Florentini Skouloudi-Kaloutsi mit ihren Schülerinnen im Keller des Gebäudes rund 150 Webstühle, auf denen minoische Motive dargestellt wurden und die so im kollektiven Gedächtnis und der Ästhetik der Kreter unvergänglich wurden.",
      description_fra: "Le bâtiment récemment rénové du consul français Blanc nous offre la possibilité de réfléchir et d'imaginer la dimension magnifique du faubourg oriental de La Canée, telle qu'elle s'était formée au cours des dernières décennies du XIXe siècle. Le bâtiment a une longue histoire : il fut fondé en 1870 par l'ingénieur Leonidas Lygkounis, qui en fit la dot de sa fille Erasmia lorsqu'elle épousa Paul Blanc, le consul français en Crète, qui vécut à La Canée de 1886 à 1901. À travers ses archives photographiques, il légua aux générations suivantes des images très importantes de La Canée et notamment de Halépa, à une époque où La Canée était au cœur des développements géopolitiques. Pendant de nombreuses décennies, dans le sous-sol du bâtiment, l'importante artiste tisserande Florentini Skouloudi-Kaloutsi faisait fonctionner avec ses élèves environ 150 métiers à tisser représentant des motifs minoens, les rendant indélébiles dans la mémoire collective et l'esthétique des Crétois.",
      position: [35.517513017503475, 24.039337431366167],
      icon: "location_icon",
      className: "consulate",
      image_source: " ",
    },
    {
      id: 6,
      name: "To Παλάτι Πρίγκιπα Γεωργίου",
      name_eng: "The Palace of Prince George",
      name_ger: "Der Palast von Prinz Georg",
      name_fra: "Le Palais du Prince Georges",
      description: "Το Παλάτι ή 'Παλατάκι' λόγω του μικρού του μεγέθους,  του Πρίγκιπα Γεωργίου  χτίστηκε στα τέλη του 19ου αιώνα για λογαριασμό και αυτό του Θεμιστοκλή Μιτσοτάκη και λόγω της μεγαλοπρέπειά του, ήταν το ιδανικότερο κτίριο για να φιλοξενήσει τον Πρίγκιπα Γεώργιο, τον δεύτερο γιο του βασιλιά Γεωργίου Α' της Ελλάδας, όταν ο πρώτος ήρθε στα Χανιά το 1898, προκειμένου να διοικήσει ως Ύπατος Αρμοστής την Κρητική Πολιτεία (1898-1913). Η μεγαλόπρεπη αυλή του, καθώς και τα πολυτελή υλικά που χρησιμοποιήθηκαν για να την κατασκευή του, μαρτυρούν τις ένδοξες εποχές που 'βίωσε' αυτό το κτίσμα. Κατά την περίοδο της κατοχής, οι ναζί Γερμανοί το είχαν επιτάξει, όπως άλλωστε και τα περισσότερα πολυτελή κτίρια της Χαλέπας και στέγασαν εκεί το Στρατηγείο τους. ",
      description_eng: "The Palace of Prince George: The Palace, or 'Palataki' ('Little Palace') due to its small size, of Prince George was built at the end of the 19th century, also on behalf of Themistoklis Mitsotakis. Owing to its grandeur, it was the most ideal building to host Prince George, the second son of King George I of Greece, when the latter came to Chania in 1898 to govern the Cretan State as High Commissioner (1898–1913). Its magnificent courtyard, as well as the luxurious materials used in its construction, bear witness to the glorious eras this building 'experienced.' During the occupation, the Nazi Germans requisitioned it — as they did with most of Halepa's luxurious buildings — and housed their Headquarters there.",
      description_ger: "Der Palast oder das 'Palataki' (Kleines Schloss), wie er wegen seiner geringen Größe genannt wird, wurde Ende des 19. Jahrhunderts ebenfalls im Auftrag von Themistoklis Mitsotakis erbaut. Aufgrund seiner Pracht war er das ideale Gebäude, um Prinz Georg, den zweiten Sohn von König Georg I. von Griechenland, zu beherbergen, als dieser 1898 nach Chania kam, um den Kretischen Staat als Hochkommissar zu regieren (1898–1913). Der prächtige Innenhof sowie die bei seiner Konstruktion verwendeten luxuriösen Materialien zeugen von den glorreichen Epochen, die dieses Gebäude 'erlebt' hat. Während der Besatzungszeit wurde es von den nationalsozialistischen Deutschen beschlagnahmt — wie die meisten Luxusgebäude in Halepa — und beherbergte dort ihr Hauptquartier.",
      description_fra: "Le Palais, ou « Palataki » (Petit Palais) en raison de sa taille modeste, fut construit à la fin du XIXe siècle, également pour le compte de Themistoklis Mitsotakis. En raison de sa grandeur, c'était le bâtiment le plus approprié pour accueillir le Prince Georges, le deuxième fils du roi Georges Ier de Grèce, lorsque celui-ci vint à La Canée en 1898 pour gouverner l'État crétois en tant que Haut-Commissaire (1898–1913). Sa magnifique cour intérieure, ainsi que les matériaux luxueux utilisés pour sa construction, témoignent des époques glorieuses que ce bâtiment a « vécues ». Pendant l'occupation, les nazis allemands le réquisitionnèrent — comme la plupart des bâtiments de luxe de Halépa — et y installèrent leur quartier général.",
      position: [35.51865, 24.03831],
      icon: "location_icon",
      className: "palace",
      image_source: " ",
    },
    {
      id: 7,
      name: "Γερμανικό Προξενείο",
      name_eng: "The German Consulate",
      name_ger: "Das Deutsche Konsulat",
      name_fra: "Le Consulat Allemand",
      description: "Το κτίριο που στέγαζε το γερμανικό προξενείο μέχρι και την περίοδο της Κρητικής Πολιτείας κατασκευάστηκε το 1870 από οθωμανό ανώτατο αξιωματούχο. Διέμενε στο κτίριο αυτό και ο Ρεούφ Πασάς των Χανίων, ο δημιουργός του Δημοτικού Κήπου.  Αποτέλεσε τη διπλωματική βάση του γερμανικού κράτους στα Χανιά, ακόμα και την περίοδο της ναζισμού. Κατά τη γερμανική κατοχή της Κρήτης στέγασε την Γενική διοίκηση των κατοχικών αρχών και φημολογείται ότι φιλοξένησε τον Έρβιν Ρόμελ κατά την επιστροφή του από το βορειο αφρικανικό μέτωπο.",
      description_eng: "The building that housed the German Consulate up until the period of the Cretan State was built in 1870 by a high-ranking Ottoman official. Reouf Pasha of Chania, the creator of the Municipal Garden, also lived in this building. It served as the diplomatic base of the German state in Chania, even during the Nazi era. During the German occupation of Crete, it housed the General Administration of the occupation authorities, and it is rumored to have hosted Erwin Rommel during his return from the North African front.",
      description_ger: "Das Gebäude, das das Deutsche Konsulat bis zur Periode der Kretischen Republik beherbergte, wurde 1870 von einem hochrangigen osmanischen Beamten erbaut. Auch Reouf Pascha von Chania, der Schöpfer des Stadtgartens, lebte in diesem Gebäude. Es diente als diplomatische Basis des deutschen Staates in Chania, sogar während der NS-Zeit. Während der deutschen Besatzung Kretas beherbergte es die Generalverwaltung der Besatzungsbehörden, und es wird gemunkelt, dass Erwin Rommel hier bei seiner Rückkehr von der nordafrikanischen Front zu Gast war.",
      description_fra: "Le bâtiment qui abritait le consulat allemand jusqu'à la période de l'État crétois fut construit en 1870 par un haut fonctionnaire ottoman. Reouf Pacha de La Canée, le créateur du Jardin Municipal, y résidait également. Il servit de base diplomatique de l'État allemand à La Canée, même pendant l'ère nazie. Durant l'occupation allemande de la Crète, il abrita l'Administration générale des autorités d'occupation, et la rumeur veut qu'Erwin Rommel y ait séjourné lors de son retour du front nord-africain.",
      position: [35.51775, 24.0355],
      icon: "location_icon",
      className: "consulate",
      image_source: " ",
    },
    {
      id: 8,
      name: "Το Βρετανικό Προξενείο",
      name_eng: "The British Consulate",
      name_ger: "Das Britische Konsulat",
      name_fra: "Le Consulat Britannique",
      description: "Χτισμένο για λογαριασμό του Θεμιστοκλή Μητσοτάκη στα τέλη του 19ου αιώνα, το οποίο κληροδότησε στην κόρη του Φαιναρέτη. Σε αυτό διέμεινε ο πρίγκιπας Γεώργιος και πολλοί άλλοι πολιτικοί από τη δεκαετία του 1990 και μετά, αφότου μετατράπηκε σε ξενοδοχείο, καθώς πληρούσε εσωτερικά και εξωτερικά όλες τις προϋποθέσεις αισθητικής και μεγαλοπρέπειας. Φυσικά, για κάποια χρόνια, την περίοδο της Κρητικής Πολιτείας στέγασε και αυτό το πολυτελές κτίσμα το βρετανικό προξενείο, με το οποίο έχει ταυτιστεί από την κοινωνία της Χαλέπας.",
      description_eng: "Built on behalf of Themistoklis Mitsotakis at the end of the 19th century, who bequeathed it to his daughter Phenarete. Prince George stayed here, as did many other politicians from the 1990s onward, after it was converted into a hotel, since it met all the aesthetic and grandeur requirements both internally and externally. Naturally, for some years during the period of the Cretan State, this luxurious building also housed the British Consulate, with which it has been identified by the community of Halepa.",
      description_ger: "Ende des 19. Jahrhunderts im Auftrag von Themistoklis Mitsotakis erbaut, der es seiner Tochter Phenarete vermachte. Prinz Georg wohnte hier, ebenso wie viele andere Politiker ab den 1990er Jahren, nachdem es in ein Hotel umgewandelt worden war, da es sowohl innen als auch außen alle ästhetischen und repräsentativen Anforderungen erfüllte. Natürlich beherbergte dieses prachtvolle Gebäude einige Jahre lang, während der Kretischen Republik, auch das Britische Konsulat, mit dem es von der Gesellschaft Halepas identifiziert wird.",
      description_fra: "Construit pour le compte de Themistoklis Mitsotakis à la fin du XIXe siècle, qui le légua à sa fille Phenarete. Le Prince Georges y séjourna, ainsi que de nombreux autres hommes politiques à partir des années 1990, après sa transformation en hôtel, car il répondait à toutes les exigences esthétiques et de grandeur, tant à l'intérieur qu'à l'extérieur. Naturellement, pendant quelques années, durant la période de l'État crétois, ce luxueux bâtiment abrita également le consulat britannique, auquel il est identifié par la communauté de Halépa.",
      position: [35.51789, 24.03618],
      icon: "location_icon",
      className: "consulate",
      image_source: " ",
    },
    {
      id: 9,
      name: "H Γερμανόφωνη καθολική εκκλησία",
      name_eng: "The German-speaking Catholic Church",
      name_ger: "Die Deutschsprachige Katholische Kirche",
      name_fra: "L'Église Catholique Germanophone",
      description: "",
      description_eng: "",
      description_ger: "",
      description_fra: "",
      position: [35.51786, 24.03915],
      icon: "location_icon",
      className: "church",
      image_source: " ",
    },
    {
      id: 10,
      name: "Πλατεία Έλενα Βενιζέλου",
      name_eng: "Elena Venizelos Square",
      name_ger: "Elena-Venizelos-Platz",
      name_fra: "Place Elena Venizelos",
      description: "",
      description_eng: "",
      description_ger: "",
      description_fra: "",
      position: [35.51786, 24.03875],
      icon: "location_icon",
      className: "square",
      image_source: " ",
    },
    {
      id: 11,
      name: "Εθνικό Ιδρυμα Ερευνών & Μελετών 'Ελευθέριος Βενιζέλος'",
      name_eng: "National Research & Studies Foundation 'Eleftherios Venizelos'",
      name_ger: "Nationales Forschungs- und Studienzentrum 'Eleftherios Venizelos'",
      name_fra: "Fondation Nationale de Recherches et d'Études 'Eleftherios Venizelos'",
      description: "Η πρώην οικία Μπλούμ κατασκευάστηκε στα μέσα του 19ου αιώνα από τον ομογενή έμπορο της Βεγγάζης, Εμμανουήλ Μπλούμ. Κατά την περίοδο της Κρητικής Πολιτείας στέγασε για λίγο καιρό το ιταλικό προξενείο, ενώ μετά τον θάνατο του Μπλούμ το 1911, μέρος της ιδιοκτησίας πέρασε στην ελληνική κοινότητα της Βεγγάζης, ώσπου το όλο συγκρότημα αγοράστηκε από το Ίδρυμα Βενιζέλος και από το 2005 μετά από ανακαίνιση του κτιρίου στέγασε όλες τις λειτουργίες του ιδρύματος. ",
      description_eng: "The former Bloum residence was built in the mid-19th century by Emmanuel Bloum, a diaspora merchant from Benghazi. During the period of the Cretan State, it briefly housed the Italian Consulate, and after Bloum's death in 1911, part of the property passed to the Greek community of Benghazi, until the entire complex was purchased by the Venizelos Foundation. Since 2005, following renovation, the building has housed all the foundation's functions.",
      description_ger: "Die ehemalige Residenz Bloum wurde Mitte des 19. Jahrhunderts von Emmanuel Bloum, einem Diaspora-Kaufmann aus Bengasi, erbaut. Während der Kretischen Republik beherbergte sie kurzzeitig das Italienische Konsulat, und nach Bloums Tod im Jahr 1911 ging ein Teil des Eigentums an die griechische Gemeinde von Bengasi über, bis der gesamte Komplex von der Venizelos-Stiftung erworben wurde. Seit 2005 beherbergt das renovierte Gebäude alle Funktionen der Stiftung.",
      description_fra: "L'ancienne résidence Bloum fut construite au milieu du XIXe siècle par Emmanuel Bloum, un marchand de la diaspora originaire de Benghazi. Durant la période de l'État crétois, elle abrita brièvement le consulat italien, et après la mort de Bloum en 1911, une partie de la propriété passa à la communauté grecque de Benghazi, jusqu'à ce que l'ensemble du complexe soit acheté par la Fondation Venizelos. Depuis 2005, après rénovation, le bâtiment abrite toutes les fonctions de la fondation.",
      position: [35.518, 24.03888],
      icon: "location_icon",
      className: "institution",
      image_source: " ",
    },
    {
      id: 12,
      name: "Οικία Μαρκαντωνάκη",
      name_eng: "The Markantonakis Residence",
      name_ger: "Das Markantonakis-Haus",
      name_fra: "La Résidence Markantonakis",
      description: "Η Οικία της οικογένειας Μαρκαντωνάκη στη Χαλέπα Χανίων,κατασκευάστηκε αρχικά και αυτή από τον Λεωνίδα Λυγκούνη το 1883. Ο Λυγκούνης το κληροδότησε στην κόρη του Ερριέτα, η οποία παντρεύτηκε τον Πέτρο Μαρκαντωνάκη και έτσι έμεινε στην ιστορία της πόλης ως η οικία Μαρκαντωνάκη. Αποτελεί ιστορική βίλα της περιοχής, με ιδιαίτερη αρχιτεκτονική και με έναν υπέροχο κήπο με εντυπωσιακές αροκάριες. Το 1901, στο σπίτι αυτό διέμενε για ένα διάστημα ο Γάλλος Συνταγματάρχης Émile Honoré Destelle, ο οποίος και απεικονίζεται στο φωτογραφικό στιγμιότυπο. Σήμερα, αποτελεί ιδιωτική κατοικία. ",
      description_eng: "The home of the Markantonakis family in Halepa, Chania, was also originally built by Leonidas Lygkounis in 1883. Lygkounis bequeathed it to his daughter Errieta, who married Petros Markantonakis — and so it has remained in the city's history as the Markantonakis Residence. It is a historic villa of the area, with distinctive architecture and a wonderful garden featuring impressive araucaria trees. In 1901, the French Colonel Émile Honoré Destelle stayed in this house for a time and is depicted in the photographic snapshot. Today, it is a private residence.",
      description_ger: "Das Haus der Familie Markantonakis in Halepa, Chania, wurde ebenfalls ursprünglich 1883 von Leonidas Lygkounis erbaut. Lygkounis vermachte es seiner Tochter Errieta, die Petros Markantonakis heiratete — und so ist es in der Geschichte der Stadt als Markantonakis-Haus bekannt geblieben. Es ist eine historische Villa der Gegend mit besonderer Architektur und einem wunderschönen Garten mit beeindruckenden Araukarien. Im Jahr 1901 wohnte der französische Oberst Émile Honoré Destelle eine Zeit lang in diesem Haus und ist auf dem Fotoschnappschuss abgebildet. Heute ist es ein Privatwohnhaus.",
      description_fra: "La maison de la famille Markantonakis à Halépa, La Canée, fut également construite à l'origine par Leonidas Lygkounis en 1883. Lygkounis la légua à sa fille Errieta, qui épousa Petros Markantonakis — et c'est ainsi qu'elle est restée dans l'histoire de la ville sous le nom de Résidence Markantonakis. C'est une villa historique du quartier, à l'architecture distinctive et au magnifique jardin orné d'impressionnants araucarias. En 1901, le colonel français Émile Honoré Destelle séjourna dans cette maison pendant un certain temps et est représenté sur le cliché photographique. Aujourd'hui, c'est une résidence privée.",
      position: [35.51691, 24.03946],
      icon: "location_icon",
      className: "house",
      image_source: " ",
    },
    {
      id: 13,
      name: "Βίλλα Σβαρτς",
      name_eng: "Villa Swartz",
      name_ger: "Villa Schwartz",
      name_fra: "Villa Schwartz",
      description: "Η μεγαλόπρεπης αυτή βίλα με τους ιωνικούς κίονες ταυτίστηκε με την Ελπίδα Μέλαινα, Marie Espérance von Schwartz, η οποία την αγόρασε το 1875 και διέμεινε σε αυτήν εκεί μέχρι τα τέλη του 1880, όταν άφησε για πάντα την αγαπημένη της Χαλέπα, μετά από 20 χρόνια σχεδόν συνεχής κατοίκησης. Συγγραφέας, περιηγήτρια, φιλοκρήσσα και γαριβαλδινή, η Ελπίδα Μέλαινα αγάπησε τη Χαλέπα και στήριξε με ανιδιοτέλεια τους κρητικούς αγωνιστές κατά την επανάσταση του 1866-67 και φρόντισε για πολλά χρόνια τα αδέσποτα ζώα της πόλη μας.  Μετέπειτα, η βίλλα πέρασε στην ιδιοκτησία του γερμανού προξένου Ριχάρδου  Κρούγκερ, όπου και διέμενε σε αυτή ο μυστηριώδης και ντυμένος πάντα στα λευκά αδερφός του Μαξ. Στα υπόγειά του, την περίοδο της γερμανικής κατοχής, πολλοί Χανιώτες φυλακίστηκαν για μικρά διαστήματα από τους ναζιστές γερμανούς. Τις τελευταίες δεκαετίες το κτίριο  καταρρέει και οι ελπίδες να αναστηλωθεί ολοένα και λιγοστεύουν, παρά το γεγονός ότι έχει χαρακτηριστεί διατηρητέο.",
      description_eng: "Villa Schwartz: This magnificent villa with Ionic columns is identified with Elpida Melaina (Marie Espérance von Schwartz), who bought it in 1875 and lived there until the late 1880s, when she left her beloved Halepa forever after almost 20 years of continuous residence. A writer, traveler, philhellene, and Garibaldian, Elpida Melaina loved Halepa and selflessly supported the Cretan fighters during the revolution of 1866–67, and for many years cared for the stray animals of our city. Later, the villa passed into the ownership of the German Consul Richard Krüger, where his mysterious brother Max — who was always dressed in white — also lived. In its basement, during the German occupation, many residents of Chania were imprisoned for short periods by the Nazi Germans. In recent decades the building has been falling into ruin, and the hopes of restoring it are dwindling, despite the fact that it has been designated as a listed building.",
      description_ger: "Diese prächtige Villa mit ionischen Säulen wird mit Elpida Melaina (Marie Espérance von Schwartz) identifiziert, die sie 1875 kaufte und dort bis Ende der 1880er Jahre lebte, als sie ihr geliebtes Halepa nach fast 20 Jahren ununterbrochenen Aufenthalts für immer verließ. Als Schriftstellerin, Reisende, Philhellenin und Garibaldianerin liebte Elpida Melaina Halepa und unterstützte selbstlos die kretischen Kämpfer während der Revolution von 1866–67 und kümmerte sich viele Jahre lang um die streunenden Tiere unserer Stadt. Später ging die Villa in den Besitz des deutschen Konsuls Richard Krüger über, wo auch sein geheimnisvoller, stets in Weiß gekleideter Bruder Max wohnte. Im Keller des Gebäudes wurden während der deutschen Besatzung viele Bewohner von Chania für kurze Zeit von den nationalsozialistischen Deutschen inhaftiert. In den letzten Jahrzehnten verfällt das Gebäude zusehends, und die Hoffnungen auf eine Restaurierung schwinden, obwohl es als Denkmal eingestuft ist.",
      description_fra: "Cette magnifique villa aux colonnes ioniques est associée à Elpida Melaina (Marie Espérance von Schwartz), qui l'acheta en 1875 et y vécut jusqu'à la fin des années 1880, lorsqu'elle quitta pour toujours son Halépa bien-aimé après près de 20 ans de résidence continue. Écrivaine, voyageuse, philhellène et garibaldienne, Elpida Melaina aimait Halépa et soutint désintéressément les combattants crétois lors de la révolution de 1866–67, et prit soin pendant de nombreuses années des animaux errants de notre ville. Plus tard, la villa passa entre les mains du consul allemand Richard Krüger, où vivait également son mystérieux frère Max, toujours vêtu de blanc. Dans son sous-sol, pendant l'occupation allemande, de nombreux habitants de La Canée furent emprisonnés pour de courtes périodes par les nazis allemands. Ces dernières décennies, le bâtiment tombe en ruine et les espoirs de le restaurer s'amenuisent, malgré le fait qu'il ait été classé monument historique.",
      position: [35.51557, 24.03926],
      icon: "location_icon",
      className: "house",
      image_source: " ",
    },
    {
      id: 14,
      name: "Οικία Βαλερίου Καλούτση",
      name_eng: "Valerios Kaloutsis Residence",
      name_ger: "Das Haus von Valerios Kaloutsis",
      name_fra: "La Résidence de Valerios Kaloutsis",
      description: "Το νεοκλασικό αυτό διώροφο κτίριο κατασκευάστηκε  στις αρχές του 20ου αιώνα από τον Βαλέριο Καλούτση, τον μετέπειτα σύζυγο της Φλωρεντίνης Σκουλούδη- Καλούτση. Το πλούσιο σε διάκοσμο αυτό κτίριο φιλοξένησε μεγάλες προσωπικότητες της κρητικής κοινωνίας μέχρι να αποτελέσει από τα μέσα του 20ου αιώνα την κύρια κατοικία και εργαστήριο της Φλωρεντίνης. Γιος της Φλωρεντίνης ήταν ο σπουδαίος εικαστικός και ζωγράφος Βαλέριος Καλούτσης. Η Φλωρεντίνη Καλούτση, εκτός του ότι αναβίωσε την μινωική αισθητική και τέχνη στα χειροποίητα υφαντά του εργαστηρίου της, έδωσε τη δυνατότητα σε Χανιώτισσες αφενός να εργαστούν και αφετέρου να βιώσουν τα πρώτα ψήγματα της γυναικείας  χειραφέτησης.",
      description_eng: "This neoclassical two-story building was constructed in the early 20th century by Valerios Kaloutsis, the future husband of Florentini Skouloudi-Kaloutsi. Richly decorated, this building hosted great personalities of Cretan society until, from the mid-20th century onward, it became Florentini's main residence and workshop. Florentini's son was the great visual artist and painter Valerios Kaloutsis. Florentini Kaloutsi, in addition to reviving Minoan aesthetics and art in the handmade textiles of her workshop, gave the women of Chania the opportunity both to work and to experience the first glimmers of female emancipation.",
      description_ger: "Dieses neoklassizistische zweistöckige Gebäude wurde zu Beginn des 20. Jahrhunderts von Valerios Kaloutsis, dem späteren Ehemann von Florentini Skouloudi-Kaloutsi, erbaut. Das reich verzierte Gebäude beherbergte bedeutende Persönlichkeiten der kretischen Gesellschaft, bis es ab Mitte des 20. Jahrhunderts zur Hauptresidenz und Werkstatt von Florentini wurde. Florentinis Sohn war der bedeutende Bildkünstler und Maler Valerios Kaloutsis. Florentini Kaloutsi hat nicht nur die minoische Ästhetik und Kunst in den handgefertigten Webstoffen ihrer Werkstatt wiederbelebt, sondern auch den Frauen von Chania die Möglichkeit gegeben, zu arbeiten und die ersten Anzeichen der Frauenemanzipation zu erleben.",
      description_fra: "Ce bâtiment néoclassique à deux étages fut construit au début du XXe siècle par Valerios Kaloutsis, le futur époux de Florentini Skouloudi-Kaloutsi. Richement décoré, ce bâtiment accueillit de grandes personnalités de la société crétoise jusqu'à devenir, à partir du milieu du XXe siècle, la résidence principale et l'atelier de Florentini. Le fils de Florentini était le grand artiste plasticien et peintre Valerios Kaloutsis. Florentini Kaloutsi, en plus de faire revivre l'esthétique et l'art minoens dans les textiles artisanaux de son atelier, a donné aux femmes de La Canée la possibilité de travailler et de vivre les premières lueurs de l'émancipation féminine.",
      position: [35.51606, 24.03855],
      icon: "location_icon",
      className: "house",
      image_source: " ",
    },
    {
      id: 15,
      name: "Κατσαμπάς",
      name_eng: "Katsampas",
      name_ger: "Katsampas",
      name_fra: "Katsampas",
      description: "Μια ιστορική γωνιά της Χαλέπας, σταυροδρόμι συνοικιών και σημείο συνάντησης των Χανιωτών,όπου κατοικούσαν σπουδαίες  προσωπικότητες της πόλης μας, αλλά και συνδέθηκε με ένα ιδιαίτερο και πολύνεκρο πολεμικό γεγονός. Τον Σεπτέμβριο του 1942, ένα βρετανικό αεροσκάφος, βαλλόμενο από γερμανικά αντιαεροπορικά έριψε για άγνωστο λόγο (μία θεωρία είναι ότι ήθελε να πλήξει τα στρατιωτικά οχήματα των Γερμανών που ήταν σταθμευμένα στον κήπο της Αγίας Μαγδαληνής) τις βόμβες που μετέφερε στην πλατεία του Κατσαμπά, με αποτέλεσμα να σκοτωθούν πάνω από 30 άμαχοι, οι οποίοι βρίσκονταν εκείνη της στιγμή στα παρακείμενα εμπορικά καταστήματα. Μία από τα σοβαρότερα αεροπορικά πλήγματα στην πόλη των Χανίων, μακριά από το κέντρο της πόλης.  ",
      description_eng: "A historic corner of Halepa, a crossroads of neighborhoods and a meeting point for the people of Chania, where many distinguished personalities of our city lived — but also a place linked to a particular and deadly wartime event. In September 1942, a British aircraft, under fire from German anti-aircraft guns, dropped — for unknown reasons (one theory is that it intended to strike the German military vehicles parked in the garden of Agia Magdalini) — the bombs it was carrying onto the square of Katsambas, resulting in the deaths of more than 30 civilians who were at that moment in the surrounding shops. It was one of the most serious aerial strikes on the city of Chania, far from the city center.",
      description_ger: "Eine historische Ecke von Halepa, ein Kreuzungspunkt der Stadtteile und ein Treffpunkt für die Bewohner von Chania, wo viele angesehene Persönlichkeiten unserer Stadt lebten — aber auch ein Ort, der mit einem besonderen und tödlichen Kriegsereignis verbunden ist. Im September 1942 warf ein britisches Flugzeug, das von deutschen Flugabwehrgeschützen beschossen wurde, aus unbekannten Gründen (eine Theorie besagt, dass es die deutschen Militärfahrzeuge im Garten der Agia Magdalini treffen wollte) seine Bomben auf den Platz von Katsambas, was zum Tod von mehr als 30 Zivilisten führte, die sich zu diesem Zeitpunkt in den umliegenden Geschäften aufhielten. Es war einer der schwersten Luftangriffe auf die Stadt Chania, weit vom Stadtzentrum entfernt.",
      description_fra: "Un coin historique de Halépa, carrefour de quartiers et lieu de rencontre pour les habitants de La Canée, où vécurent de nombreuses personnalités distinguées de notre ville — mais aussi un lieu lié à un événement guerrier particulier et meurtrier. En septembre 1942, un avion britannique, sous le feu des canons antiaériens allemands, largua — pour des raisons inconnues (une théorie veut qu'il ait voulu frapper les véhicules militaires allemands garés dans le jardin d'Agia Magdalini) — les bombes qu'il transportait sur la place de Katsambas, causant la mort de plus de 30 civils qui se trouvaient à ce moment-là dans les boutiques environnantes. Ce fut l'un des bombardements aériens les plus graves sur la ville de La Canée, loin du centre-ville.",
      position: [35.51516, 24.03793],
      icon: "location_icon",
      className: "area",
      image_source: " ",
    },
    {
      id: 16,
      name: "O Ιερός Ναός Αγίας Μαρίας Μαγδαληνής",
      name_eng: "The Holy Church of St. Mary Magdalene",
      name_ger: "Die Heilige Kirche der Heiligen Maria Magdalena",
      name_fra: "L'Église Sainte-Marie-Madeleine",
      description: "Η εκκλησία της Αγίας Μαρίας της Μαγδαληνής, ο λεγόμενος «ηγεμονικός ναός», κτίστηκε, όταν ο Ύπατος Αρμοστής (Ηγεμόνας) της Κρήτης Πρίγκιπας Γεώργιος, του οποίου η μητέρα ήταν η Όλγα, ρωσίδα και Βασίλισσα των Ελλήνων, προσέφερε στις αρχές του 1901 δέκα χιλιάδες ρούβλια και τα σχέδια για την ανέγερση μιας εκκλησίας, σε ανάμνηση της διαμονής στα Χανιά της αδελφής του Μαρίας, συζύγου του Μεγάλου Δούκα της Ρωσίας Γεωργίου. (πηγή 3) Έχει έντονες και σαφείς αρχιτεκτονικές επιρροές από την παραδοσιακή ρωσική ναοδομία, ιδιαίτερα εμφανείς στο τμήμα του τρούλου. Στο ναό αυτό μεταφέρθηκε η σορός του Ελευθερίου Βενιζέλου, προκειμένου να τεθεί προς λαϊκό προσκύνημα, ενώ ο κήπος του χρησιμοποιήθηκε από τον γερμανικό στρατό ως όρχος στρατιωτικών οχημάτων κατά την περίοδο της ναζιστικής κατοχής (1941-1945). ",
      description_eng: "The church of St. Mary Magdalene, the so-called 'princely church,' was built when the High Commissioner (Hegemon) of Crete, Prince George — whose mother was Olga, a Russian and Queen of the Hellenes — offered, in early 1901, ten thousand rubles and the plans for the construction of a church, in commemoration of the stay in Chania of his sister Maria, wife of Grand Duke George of Russia. (source 3) It bears strong and clear architectural influences from traditional Russian church architecture, particularly visible in the dome. The body of Eleftherios Venizelos was brought to this church to lie in state for public veneration, while its garden was used by the German army as a depot for military vehicles during the Nazi occupation (1941–1945).",
      description_ger: "Die Kirche der Heiligen Maria Magdalena, die sogenannte 'Fürstenkirche', wurde gebaut, als der Hochkommissar (Hegemon) von Kreta, Prinz Georg — dessen Mutter Olga, eine Russin und Königin der Hellenen, war — Anfang 1901 zehntausend Rubel und die Pläne für den Bau einer Kirche zur Erinnerung an den Aufenthalt seiner Schwester Maria, der Gemahlin von Großherzog Georg von Russland, in Chania anbot. (Quelle 3) Sie weist starke und klare architektonische Einflüsse der traditionellen russischen Kirchenbaukunst auf, die besonders an der Kuppel sichtbar sind. Der Leichnam von Eleftherios Venizelos wurde in diese Kirche überführt, um für die Öffentlichkeit aufgebahrt zu werden, während der Garten während der nationalsozialistischen Besatzung (1941–1945) vom deutschen Militär als Depot für Militärfahrzeuge genutzt wurde.",
      description_fra: "L'église Sainte-Marie-Madeleine, la soi-disant « église princière », fut construite lorsque le Haut-Commissaire (Hégémon) de Crète, le Prince Georges — dont la mère était Olga, une Russe et Reine des Hellènes — offrit, début 1901, dix mille roubles et les plans pour la construction d'une église, en commémoration du séjour à La Canée de sa sœur Maria, épouse du Grand-Duc Georges de Russie. (source 3) Elle présente de fortes et claires influences architecturales de l'architecture ecclésiastique russe traditionnelle, particulièrement visibles dans le dôme. Le corps d'Eleftherios Venizelos fut apporté dans cette église pour être exposé à la vénération publique, tandis que son jardin fut utilisé par l'armée allemande comme dépôt de véhicules militaires pendant l'occupation nazie (1941–1945).",
      position: [35.5175, 24.03818],
      icon: "location_icon",
      className: "church",
      image_source: " ",
    },
    {
      id: 17,
      name: "To Αυτοδιαχειριζόμενο Στέκι στη Χαλέπα",
      name_eng: "The Self-Managed Social Center of Chania ",
      name_ger: "Das Selbstverwaltete Sozialzentrum von Chania",
      name_fra: "Le Centre Social Autogéré de La Canée",
      description: "Άλλο ένα τοπόσημο της σύγχρονης ιστορία της Χαλέπας ήταν και το Αυτοδιαχειριζόμενο Στέκι Χανίων. Για δέκα χρόνια, από το 1996 μέχρι το 2006 στεγάστηκε στο κτίριο αυτό η πρώτη συλλογικότητα οριζόντιας συνέλευσης στα Χανιά, η οποία δραστηριοποιήθηκε σε ζητήματα πολιτικά, οικολογικά και συνδικαλιστικά, παρεμβαίνοντας δυναμικά και με πολιτικά προτάγματα σε όλη την Κρήτη, όπου αυτό κρινόταν απαραίτητο από το μοναδικό της πολιτικό όργανο, την εβδομαδιαία της συνέλευση. Το 'Μαύρο Ρίφι' ήταν για χρόνια το περιοδικό του έντυπο. ",
      description_eng: "Another landmark of Halepa's modern history was the Self-Managed Social Center of Chania. For ten years, from 1996 to 2006, this building housed the first horizontal-assembly collective in Chania, which was active on political, ecological, and union issues, intervening dynamically and with political agendas throughout Crete wherever this was deemed necessary by its sole political body — its weekly assembly. 'Mavro Rifi' (Black Reef) was for years its printed magazine. ",
      description_ger: "Ein weiteres Wahrzeichen der modernen Geschichte von Halepa war das Selbstverwaltete Sozialzentrum von Chania. Zehn Jahre lang, von 1996 bis 2006, beherbergte dieses Gebäude das erste basisdemokratische Kollektiv in Chania, das sich in politischen, ökologischen und gewerkschaftlichen Fragen engagierte und dynamisch und mit politischen Agenden in ganz Kreta intervenierte, wo immer dies von seinem einzigen politischen Gremium — der Wochenversammlung — für notwendig erachtet wurde. 'Mavro Rifi' (Schwarzes Riff) war jahrelang seine gedruckte Zeitschrift.",
      description_fra: "Un autre point de repère de l'histoire moderne de Halépa était le Centre Social Autogéré de La Canée. Pendant dix ans, de 1996 à 2006, ce bâtiment accueillit le premier collectif à assemblée horizontale de La Canée, qui était actif sur des questions politiques, écologiques et syndicales, intervenant de manière dynamique et avec des agendas politiques dans toute la Crète là où cela était jugé nécessaire par son seul organe politique — son assemblée hebdomadaire. « Mavro Rifi » (Récif Noir) fut pendant des années son magazine imprimé.",
      position: [35.518310, 24.037127],
      icon: "location_icon",
      className: "house",
      image_source: " ",
    },
];

  export default pois;